// Web game audio. Card Duel has its own original soundtrack and event set;
// every MP3 is generated by tools/generateDuelAudio.py and is byte-identical
// to Android. Audio remains fire-and-forget so autoplay/codec failures can
// never interrupt authoritative gameplay.
const FILES = [
  'move', 'move_opponent', 'drop', 'flip', 'match_found', 'your_turn',
  'tick', 'tick_urgent', 'timeout', 'win', 'lose', 'draw', 'tap',
  'duel_lock', 'duel_intro', 'duel_round_win', 'duel_round_lose',
  'duel_round_draw', 'duel_final_draw', 'duel_victory', 'duel_defeat',
];

const KEY = 'game_sound_enabled';
const cache = {};
let enabled = localStorage.getItem(KEY) !== '0';
let duelMusic = null;
let duelMusicRequested = false;

const source = name => `/sfx/${name}.mp3`;

function get(name) {
  if (!cache[name]) {
    const a = new Audio(source(name));
    a.preload = 'auto';
    cache[name] = a;
  }
  return cache[name];
}

export function isEnabled() {
  return enabled;
}

function beginMusic() {
  if (!enabled || !duelMusicRequested) return;
  try {
    duelMusic ||= new Audio('/sfx/duel_music.mp3');
    duelMusic.preload = 'auto';
    duelMusic.loop = true;
    duelMusic.volume = 0.20;
    const attempt = duelMusic.play();
    // If the socket event fell outside the browser's gesture window, retry
    // exactly once on the next real tap instead of leaving the match silent.
    if (attempt?.catch) attempt.catch(() => {
      const unlock = () => {
        document.removeEventListener('pointerdown', unlock);
        if (enabled && duelMusicRequested) duelMusic?.play()?.catch?.(() => {});
      };
      document.addEventListener('pointerdown', unlock, { once: true });
    });
  } catch { /* never let audio break the game */ }
}

export function startDuelMusic() {
  duelMusicRequested = true;
  beginMusic();
}

export function stopDuelMusic() {
  duelMusicRequested = false;
  try {
    if (duelMusic) { duelMusic.pause(); duelMusic.currentTime = 0; }
  } catch { /* cosmetic */ }
}

export function setEnabled(v) {
  enabled = !!v;
  localStorage.setItem(KEY, enabled ? '1' : '0');
  if (!enabled) {
    Object.values(cache).forEach(a => {
      try { a.pause(); a.currentTime = 0; } catch { /* ignore */ }
    });
    try { duelMusic?.pause(); } catch { /* ignore */ }
  } else if (duelMusicRequested) {
    beginMusic();
  }
  return enabled;
}

export function play(name, volume = 1) {
  if (!enabled || !FILES.includes(name)) return;
  try {
    const base = get(name);
    // Clone so impact and result layers can overlap without cutting off.
    const a = base.cloneNode();
    a.volume = Math.max(0, Math.min(1, volume));
    const p = a.play();
    if (p?.catch) p.catch(() => { /* autoplay blocked until first tap */ });
  } catch { /* never let audio break the game */ }
}
