// Web game audio. Card Duel has its own original soundtrack and event set;
// every MP3 is generated by tools/generateDuelAudio.py and is byte-identical
// to Android. Audio remains fire-and-forget so autoplay/codec failures can
// never interrupt authoritative gameplay.
const FILES = [
  'move', 'move_opponent', 'drop', 'flip', 'match_found', 'your_turn',
  'tick', 'tick_urgent', 'timeout', 'win', 'lose', 'draw', 'tap',
  'duel_lock', 'duel_intro', 'duel_round_win', 'duel_round_lose',
  'duel_round_draw', 'duel_points', 'duel_final_draw', 'duel_victory', 'duel_defeat',
  'box_shake',
];

const KEY = 'game_sound_enabled';
const cache = {};
let enabled = localStorage.getItem(KEY) !== '0';
let duelMusic = null;
let duelMusicRequested = false;

// ── نگهبانِ ازسرگیری (دورِ ۳۲) ───────────────────────────────────────────
//
// باگی که کاربر گزارش کرد: «صدا وسطِ بازی کارت قطع می‌شود».
//
// بازتولیدِ دقیق: کاربر وسطِ دوئل به اپِ دیگری می‌رود (نوتیفیکیشن، تماس،
// عوض‌کردنِ تب). شنوندهٔ `visibilitychange` درست کار می‌کند و موزیک را
// `pause` می‌کند. تا اینجا درست. اما موقعِ برگشتن، `duelMusic.play()` را
// بیرون از پنجرهٔ ژستِ کاربر صدا می‌زنیم و مرورگرِ موبایل آن را با
// `NotAllowedError` رد می‌کند — چون بازگشت به تب «ژستِ کاربر» حساب نمی‌شود.
// نتیجه: موزیک برای همیشه خاموش می‌ماند، حتی وقتی کاربر بعداً روی کارت
// می‌زند، چون هیچ‌کس دوباره تلاش نمی‌کند. بقیهٔ افکت‌ها هم شنیده نمی‌شوند
// چون همان قفلِ autoplay روی کلون‌ها هم هست.
//
// چرا `beginMusic` به‌تنهایی کافی نبود: retry داخلِ آن فقط یک‌بار و فقط
// برای شکستِ *شروع* ثبت می‌شد؛ مسیرِ `visibilitychange` اصلاً از آن رد
// نمی‌شد و شکستش بی‌صدا بلعیده می‌شد (`?.catch?.(() => {})`).
//
// راه‌حل: یک نقطهٔ واحد `resumeOnGesture()` که هر شکستِ پخش را به شنوندهٔ
// یک‌بارمصرفِ `pointerdown` گره می‌زند. این معادلِ وبیِ همان کاری است که
// `_AudioLifecycle` روی اندروید می‌کند (اندروید مشکلِ ژست ندارد، ولی
// همان قرارداد را دارد: برگشت به پیش‌زمینه = ازسرگیری).
let unlockArmed = false;

function resumeOnGesture() {
  if (unlockArmed || typeof document === 'undefined') return;
  unlockArmed = true;
  const unlock = () => {
    unlockArmed = false;
    if (!enabled || !duelMusicRequested || !duelMusic) return;
    // اگر این تلاش هم شکست خورد، دوباره مسلح می‌شویم: کاربر ممکن است
    // اولین لمسش را جایی بزند که مرورگر هنوز قانع نشده باشد.
    duelMusic.play()?.catch?.(() => resumeOnGesture());
  };
  document.addEventListener('pointerdown', unlock, { once: true });
}

const source = name => `/sfx/${name}.mp3`;

function get(name) {
  if (!cache[name]) {
    const a = new Audio(source(name));
    a.preload = 'auto';
    cache[name] = a;
  }
  return cache[name];
}

export function isEnabled() {
  return enabled;
}

function beginMusic() {
  if (!enabled || !duelMusicRequested) return;
  try {
    duelMusic ||= new Audio('/sfx/duel_music.mp3');
    duelMusic.preload = 'auto';
    duelMusic.loop = true;
    duelMusic.volume = 0.20;
    // اگر رویدادِ سوکت بیرون از پنجرهٔ ژستِ مرورگر افتاد، به‌جای سکوتِ
    // دائمی روی لمسِ بعدی دوباره تلاش کن.
    duelMusic.play()?.catch?.(() => resumeOnGesture());
  } catch { /* never let audio break the game */ }
}

// Mirror of `_AudioLifecycle` on Android: a backgrounded tab must not keep
// the duel soundtrack running behind the user's back. `pause` rather than
// `stop` so returning resumes mid-phrase instead of restarting the loop.
//
// Registered once at module load — the listener is cheap and the guard below
// makes it a no-op whenever no duel is running.
if (typeof document !== 'undefined') {
  document.addEventListener('visibilitychange', () => {
    if (!duelMusic) return;
    if (document.visibilityState === 'hidden') {
      try { duelMusic.pause(); } catch { /* cosmetic */ }
    } else if (enabled && duelMusicRequested) {
      // 🔴 اینجا بود که صدا برای همیشه می‌مرد: مرورگرِ موبایل این
      // `play()` را رد می‌کند چون بازگشت به تب ژستِ کاربر نیست.
      // حالا شکست را به لمسِ بعدی گره می‌زنیم.
      duelMusic.play()?.catch?.(() => resumeOnGesture());
    }
  });
}

export function startDuelMusic() {
  duelMusicRequested = true;
  beginMusic();
}

export function stopDuelMusic() {
  duelMusicRequested = false;
  try {
    if (duelMusic) { duelMusic.pause(); duelMusic.currentTime = 0; }
  } catch { /* cosmetic */ }
}

export function setEnabled(v) {
  enabled = !!v;
  localStorage.setItem(KEY, enabled ? '1' : '0');
  if (!enabled) {
    Object.values(cache).forEach(a => {
      try { a.pause(); a.currentTime = 0; } catch { /* ignore */ }
    });
    try { duelMusic?.pause(); } catch { /* ignore */ }
  } else if (duelMusicRequested) {
    beginMusic();
  }
  return enabled;
}

// ── صدای لرزشِ صندوق ───────────────────────────────────────────────────
// یک المانِ جدا با loop روی فایلِ مخصوصِ لرزش؛ دقیقاً هم‌زمان با شروعِ
// انیمیشن شروع می‌شود و با `stopShake` قطع می‌شود. بدونِ loop، هم‌زمانیِ
// چند clone با تأخیرِ لود، ریتم را می‌شکست.
let _shakeAudio = null;

export function playShake() {
  if (!enabled) return;
  try {
    stopShake();
    const base = get('box_shake');
    const a = base.cloneNode();
    a.loop = true;
    a.volume = 0.85;
    a.play()?.catch?.(() => {});
    _shakeAudio = a;
  } catch { /* never let audio break the box */ }
}

export function stopShake() {
  if (!_shakeAudio) return;
  try {
    _shakeAudio.pause();
    _shakeAudio.src = '';
    _shakeAudio.removeAttribute('src');
    _shakeAudio.load();
  } catch { /* ignore */ }
  _shakeAudio = null;
}

// پیش‌لودِ چند افکتِ کوتاه تا اولین پخشِ هر کدام بی‌تأخیر باشد. چون
// `get()` همان کشِ سراسریِ بازی را پر می‌کند، بقیهٔ بازی هم سود می‌برد.
export function warmup(names) {
  if (!Array.isArray(names)) names = [names];
  names.forEach(n => { try { get(n).load(); } catch { /* ignore */ } });
}

export function play(name, volume = 1) {
  if (!enabled || !FILES.includes(name)) return;
  try {
    const base = get(name);
    // کلون می‌گیریم تا لایهٔ ضربه و لایهٔ نتیجه هم‌زمان پخش شوند و
    // همدیگر را قطع نکنند.
    //
    // 🔴 دورِ ۳۲ — نشتِ المانِ صوتی: تا پیش از این، هر کلون تا ابد زنده
    // می‌ماند. در یک دوئلِ کاملِ اندازه‌گیری‌شده ۱۱ المانِ صوتیِ رهاشده
    // شمردیم. روی موبایل تعدادِ همزمانِ المان‌های مدیا سقف دارد؛ بعد از
    // چند دست، `play()` بی‌صدا شکست می‌خورَد و کاربر می‌گوید «صدا وسطِ
    // بازی قطع شد». با آزادکردنِ کلون بعد از پایانِ پخش، سقف هرگز پر
    // نمی‌شود.
    const a = base.cloneNode();
    a.volume = Math.max(0, Math.min(1, volume));
    const release = () => {
      a.removeEventListener('ended', release);
      a.removeEventListener('error', release);
      try { a.src = ''; a.removeAttribute('src'); a.load(); } catch { /* ignore */ }
    };
    a.addEventListener('ended', release);
    a.addEventListener('error', release);
    a.play()?.catch?.(() => release());
  } catch { /* never let audio break the game */ }
}
