import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import'./style.css';

const API=import.meta.env.VITE_API_BASE||'https://api.ghelghelishop.ir';
const avatars=['avatar_1_football.png','avatar_2_trophy.png','avatar_3_star.png','avatar_4_rocket.png','avatar_5_lion.png','avatar_6_tiger.png','avatar_7_eagle.png','avatar_8_target.png','avatar_9_bolt.png','avatar_10_crown.png'];
const fa=n=>new Intl.NumberFormat('fa-IR').format(Number(n||0));
const asset=v=>!v?'':String(v).startsWith('http')?v:API+v;

async function req(path,method='GET',body,token){
  const r=await fetch(API+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined});
  const d=await r.json().catch(()=>({}));
  if(!r.ok){const err=new Error(d.message||'خطا در ارتباط با سرور');err.status=r.status;throw err}
  return d;
}

function App(){
  const[token,setToken]=useState(localStorage.token||'');
  const[mode,setMode]=useState(location.hostname.startsWith('register.')?'register':'login');
  return <div className="page"><div className="hero"><img src="/logo.png" alt="قلقلی"/><b>قلقلی</b></div>{token?<Portal token={token} logout={()=>{localStorage.removeItem('token');setToken('')}}/>:<Auth mode={mode} setMode={setMode} done={t=>{localStorage.token=t;setToken(t)}}/>}</div>;
}

function Auth({mode,setMode,done}){
  const[f,setF]=useState({mobile:'',password:'',nickname:'',currentPassword:''});const[msg,setMsg]=useState('');const[needsCurrentPassword,setNeedsCurrentPassword]=useState(false);
  async function submit(e){e.preventDefault();setMsg('');try{const d=mode==='register'?await req('/api/auth/register-password','POST',{mobile:f.mobile,password:f.password,nickname:f.nickname||undefined,profileAvatarKey:avatars[0],...(needsCurrentPassword?{currentPassword:f.currentPassword}:{})}):await req('/api/auth/login','POST',{mobile:f.mobile,password:f.password});done(d.token)}catch(x){setMsg(x.message);if(mode==='register'&&x.status===409)setNeedsCurrentPassword(true)}}
  return <form className="card auth" onSubmit={submit}><h2>{mode==='register'?'ثبت‌نام سریع':'ورود کاربر'}</h2><div className="tabs"><button type="button" className={mode==='login'?'on':''} onClick={()=>setMode('login')}>ورود</button><button type="button" className={mode==='register'?'on':''} onClick={()=>setMode('register')}>ثبت‌نام</button></div><input placeholder="شماره موبایل" value={f.mobile} onChange={e=>setF({...f,mobile:e.target.value})}/><input placeholder="رمز عبور" type="password" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/>{mode==='register'&&<><input placeholder="نام مستعار اختیاری" value={f.nickname} onChange={e=>setF({...f,nickname:e.target.value})}/><p className="hint">ثبت‌نام سریع است؛ بعد از ورود از بخش پروفایل، اطلاعات کامل را وارد می‌کنی. چون پیامک هنوز فعال نیست، اگر قبلاً با این شماره ثبت‌نام کرده‌ای رمز فعلی را هم وارد کن.</p>{needsCurrentPassword&&<input placeholder="رمز فعلی این شماره" type="password" value={f.currentPassword} onChange={e=>setF({...f,currentPassword:e.target.value})}/>}</>}<button className="main">{mode==='register'?'ثبت‌نام سریع':'ورود'}</button>{msg&&<p className="msg">{msg}</p>}</form>;
}


function Portal({token,logout}){
  const[tab,setTab]=useState('home');const[p,setP]=useState(null);const[rewards,setRewards]=useState([]);const[msg,setMsg]=useState('');const[publicUser,setPublicUser]=useState(null);
  async function load(){const pr=await req('/api/profile','GET',null,token);setP(pr);setRewards(await req('/api/rewards','GET',null,token));}
  useEffect(()=>{load()},[]);
  if(!p)return <div className="card">در حال بارگذاری...</div>;
  return <div className="portal"><nav className="mobileNav">{[['home','خانه'],['profile','پروفایل'],['rewards','جوایز'],['league','لیگ'],['chat','چت روم'],['support','پشتیبانی']].map(x=><button key={x[0]} className={tab===x[0]?'on':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}<button className="danger" onClick={logout}>خروج</button></nav>{msg&&<div className="toast">{msg}</div>}{tab==='home'&&<Home token={token} p={p} rewards={rewards} load={load} setMsg={setMsg}/>} {tab==='profile'&&<Profile token={token} p={p} load={load} setMsg={setMsg}/>} {tab==='rewards'&&<Rewards rewards={rewards}/>} {tab==='league'&&<League token={token} openProfile={setPublicUser}/>} {tab==='chat'&&<Chat token={token} openProfile={setPublicUser}/>} {tab==='support'&&<Support token={token}/>} {publicUser&&<PublicProfile token={token} userId={publicUser} close={()=>setPublicUser(null)}/>}</div>;
}

function Avatar({u,size=72}){return <img className="avatar" style={{width:size,height:size}} src={u?.profile_image_url?asset(u.profile_image_url):`/avatars/${u?.profile_avatar_key||avatars[0]}`}/>}
function Home({token,p,rewards,load,setMsg}){const[code,setCode]=useState('');const u=p.user;const sorted=[...rewards].sort((a,b)=>a.required_points-b.required_points);let next=sorted.find(r=>u.current_points<r.required_points)||sorted.at(-1);const progress=next?Math.min(1,u.current_points/next.required_points):0;async function redeem(){try{const d=await req('/api/cards/redeem','POST',{code},token);setMsg(d.message);setCode('');load()}catch(e){setMsg(e.message)}}return <div className="grid"><section className="card heroCard"><Avatar u={u}/><h2>{u.nickname||u.mobile}</h2><h1>{fa(u.current_points)} امتیاز</h1><div className="bar"><span style={{width:(progress*100)+'%'}}/></div><p>{next?`تا جایزه ${next.name}: ${fa(Math.max(0,next.required_points-u.current_points))} امتیاز مانده`:'هنوز جایزه‌ای تعریف نشده'}</p><h2>ثبت کد کارت های قلقلی</h2><p className="hint">(پک کارت های قلقلی بصورت فیزیکی در فروشگاه ها و سوپرمارکت ها به فروش می رسند.)</p><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="کد کارت"/><button className="main" onClick={redeem}>ثبت کد</button></section><section className="card"><h2>موجودی کارت‌ها</h2>{(p.inventory||[]).map(i=><div className="reward" key={i.id}><img src={asset(i.image_url)||'/avatars/avatar_1_football.png'}/><div><b>{i.name}</b><p>تعداد: {fa(i.quantity)} — {fa(i.point_value)} امتیاز</p></div></div>)}</section></div>}
function Profile({token,p,load,setMsg}){const u=p.user;const[edit,setEdit]=useState({firstName:u.first_name||'',lastName:u.last_name||'',nickname:u.nickname||'',age:u.age||'',city:u.city||'',province:u.province||'',bankAccount:u.bank_account||'',profileAvatarKey:u.profile_avatar_key||avatars[0]});const[pw,setPw]=useState({currentPassword:'',newPassword:''});const[pwMsg,setPwMsg]=useState('');async function save(){try{await req('/api/profile','PATCH',edit,token);setMsg('پروفایل ذخیره شد');load()}catch(e){setMsg(e.message)}}async function changePassword(e){e.preventDefault();setPwMsg('');try{await req('/api/profile/change-password','POST',pw,token);setPwMsg('رمز عبور با موفقیت تغییر کرد');setPw({currentPassword:'',newPassword:''})}catch(e){setPwMsg(e.message)}}return <section className="card wide"><h2>تکمیل پروفایل خصوصی</h2><p className="hint">این اطلاعات فقط برای مدیر است. در چت فقط نام مستعار و عکس دیده می‌شود.</p><div className="avatars">{avatars.map(a=><img key={a} className={edit.profileAvatarKey===a?'sel':''} src={`/avatars/${a}`} onClick={()=>setEdit({...edit,profileAvatarKey:a})}/>)}</div><div className="formgrid"><input placeholder="نام" value={edit.firstName} onChange={e=>setEdit({...edit,firstName:e.target.value})}/><input placeholder="نام خانوادگی" value={edit.lastName} onChange={e=>setEdit({...edit,lastName:e.target.value})}/><input placeholder="نام مستعار" value={edit.nickname} onChange={e=>setEdit({...edit,nickname:e.target.value})}/><input placeholder="سن" value={edit.age} onChange={e=>setEdit({...edit,age:e.target.value})}/><input placeholder="استان" value={edit.province} onChange={e=>setEdit({...edit,province:e.target.value})}/><input placeholder="شهر / محل زندگی" value={edit.city} onChange={e=>setEdit({...edit,city:e.target.value})}/><input placeholder="شماره کارت بانکی / شبا" value={edit.bankAccount} onChange={e=>setEdit({...edit,bankAccount:e.target.value})}/></div><button className="main" onClick={save}>ذخیره پروفایل</button><hr className="divider"/><h2>تغییر رمز عبور</h2><p className="hint">چون فعلاً سامانه پیامک فعال نیست، بازیابی خودکار رمز در دسترس نیست؛ رمز را فقط از همینجا (با وارد کردن رمز فعلی) می‌توانید عوض کنید. اگر رمز را فراموش کرده‌اید، از پشتیبانی بخواهید رمز موقت برایتان تنظیم کند.</p><form className="formgrid" onSubmit={changePassword}><input type="password" placeholder="رمز فعلی" value={pw.currentPassword} onChange={e=>setPw({...pw,currentPassword:e.target.value})}/><input type="password" placeholder="رمز جدید (حداقل ۶ کاراکتر)" value={pw.newPassword} onChange={e=>setPw({...pw,newPassword:e.target.value})}/><button className="main" type="submit">تغییر رمز عبور</button></form>{pwMsg&&<p className="msg">{pwMsg}</p>}</section>}

function Rewards({rewards}){return <section className="card wide"><h2>جوایز</h2><div className="cards">{rewards.map(r=><div className="rewardCard" key={r.id}><img src={asset(r.image_url)||'/avatars/avatar_2_trophy.png'}/><b>{r.name}</b><p>{fa(r.required_points)} امتیاز</p><small>{r.reward_value}</small></div>)}</div></section>}
function League({token,openProfile}){
  const[d,setD]=useState(null);
  useEffect(()=>{req('/api/league/current','GET',null,token).then(setD)},[]);
  if(!d)return <div className="card leaguePage"><div className="skeleton"/>در حال بارگذاری لیگ...</div>;
  const entries=d.entries||[]; const season=d.season||{};
  const end=season.ends_at?new Date(season.ends_at):null;
  const days=end?Math.max(0,Math.ceil((end-Date.now())/86400000)):0;
  const top=entries.slice(0,3); const rest=entries.slice(3);
  return <section className="card wide leaguePage"><div className="sectionHead"><div><h2>لیگ ماهانه قلقلی</h2><p>رتبه‌بندی زنده کاربران تا پایان ماه؛ امتیاز لیگ آخر ماه ریست می‌شود، امتیاز کلی دست نمی‌خورد.</p></div><b className="countdown">{fa(days)} روز مانده</b></div><div className="podium">{top.map((e,i)=><div className={`podiumCard p${i+1}`} onClick={()=>openProfile(e.user_id)} key={e.user_id}><span className="medal">{['🥇','🥈','🥉'][i]}</span><b>{e.nickname||e.first_name||'کاربر'}</b><strong>{fa(e.points)} امتیاز</strong></div>)}</div><div className="leagueList">{rest.map((e,i)=><div className="row clickable leagueRow" key={e.user_id} onClick={()=>openProfile(e.user_id)}><b>#{fa(i+4)}</b><span>{e.nickname||e.first_name||'کاربر'}</span><strong>{fa(e.points)} امتیاز</strong></div>)}</div>{!entries.length&&<div className="empty">هنوز امتیازی در لیگ ثبت نشده است.</div>}</section>
}
function Chat({token,openProfile}){
  const[messages,setMessages]=useState([]),[stickers,setStickers]=useState([]),[text,setText]=useState(''),[err,setErr]=useState(''),[reply,setReply]=useState(null),[emojiOpen,setEmojiOpen]=useState(false);
  const emojis=['😀','😍','🔥','⚽','🏆','👏','😂','😎','❤️','👍','🎉','💚','🥇','✨','🙌','😜'];
  async function load(){try{setMessages(await req('/api/chat/messages','GET',null,token));setStickers(await req('/api/chat/stickers','GET',null,token));setErr('')}catch(e){setErr(e.message)}}
  useEffect(()=>{load();const t=setInterval(load,3000);return()=>clearInterval(t)},[]);
  async function send(stickerId=null){try{if(!stickerId&&!text.trim())return;await req('/api/chat/messages','POST',{message:text,stickerId,replyTo:reply?.id},token);setText('');setReply(null);setEmojiOpen(false);load()}catch(e){setErr(e.message)}}
  async function like(m){try{await req(`/api/chat/messages/${m.id}/like`,'POST',{},token);load()}catch(e){setErr(e.message)}}async function report(m){try{await req(`/api/chat/messages/${m.id}/report`,'POST',{},token);setErr('گزارش ثبت شد و برای مدیر ارسال می‌شود')}catch(e){setErr(e.message)}}
  return <section className="card wide chatPage"><div className="sectionHead"><div><h2>چت روم قلقلی</h2><p>کاربران در این قسمت میتوانند باهم گفتگو کنند. (از الفاظ رکیک و بحث های سیاسی جدا خودداری بشه.)</p></div><span className="liveBadge">زنده</span></div>{err&&<p className="msg">{err}</p>}{reply&&<div className="replybar">در پاسخ به {reply.nickname||'کاربر'}: {reply.message_text}<button onClick={()=>setReply(null)}>×</button></div>}<div className="stickerTray">{stickers.map(st=><button key={st.id} onClick={()=>send(st.id)} title={st.title}><img src={asset(st.image_url)}/></button>)}{!stickers.length&&<span className="hint">استیکری هنوز توسط مدیر اضافه نشده است.</span>}</div><div className="chatbox">{messages.map(m=><div className="chatmsg" key={m.id}><img onClick={()=>openProfile(m.user_id)} src={m.profile_image_url?asset(m.profile_image_url):`/avatars/${m.profile_avatar_key||avatars[0]}`}/><div className="chatbody"><b onClick={()=>openProfile(m.user_id)} className="clickableText">{m.nickname||m.first_name||'کاربر'}</b>{m.reply_text&&<small className="reply">↩ {m.reply_nickname||'کاربر'}: {m.reply_text}</small>}{m.message_type==='sticker'&&m.sticker_url?<img className="stickerMsg" src={asset(m.sticker_url)}/>:<p>{m.message_text}</p>}<div className="chatActions"><button onClick={()=>setReply(m)}>ریپلای</button><button onClick={()=>like(m)}>❤ {fa(m.like_count)}</button><button onClick={()=>report(m)}>گزارش</button></div></div></div>)}</div><div className="sendDock"><button className="emojiBtn" onClick={()=>setEmojiOpen(!emojiOpen)}>😊</button>{emojiOpen&&<div className="emojiPopover">{emojis.map(e=><button key={e} onClick={()=>setText(text+e)}>{e}</button>)}</div>}<input value={text} onChange={e=>setText(e.target.value)} placeholder="پیام..."/><button className="main" onClick={()=>send()}>ارسال</button></div></section>
}
function PublicProfile({token,userId,close}){const[u,setU]=useState(null),[err,setErr]=useState('');useEffect(()=>{req(`/api/users/${userId}/public`,'GET',null,token).then(setU).catch(e=>setErr(e.message))},[userId]);return <div className="modalShade" onClick={close}><div className="publicModal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button>{err&&<p className="msg">{err}</p>}{!u&&!err?<p>در حال بارگذاری...</p>:u&&<><div className="publicHead"><img src={u.profile_image_url?asset(u.profile_image_url):`/avatars/${u.profile_avatar_key||avatars[0]}`}/><div><h2>{u.nickname||'کاربر'}</h2><p>عضویت: {new Date(u.joined_at).toLocaleDateString('fa-IR')}</p><p>امتیاز کسب‌شده: {fa(u.lifetime_points)} | امتیاز فعلی: {fa(u.current_points)}</p></div></div><h3>کارت‌های ثبت‌شده</h3>{(!u.cards||!u.cards.length)&&<p className="hint">هنوز کارتی ثبت نکرده است.</p>}{(u.cards||[]).map(c=><div className="reward" key={c.card_type_id}><img src={asset(c.image_url)||'/avatars/avatar_1_football.png'}/><div><b>{c.name}</b><p>تعداد ثبت: {fa(c.registered_count)} — {fa(c.point_value)} امتیاز</p></div></div>)}<h3>جوایز دریافت‌شده</h3>{(!u.rewards||!u.rewards.length)&&<p className="hint">هنوز جایزه تاییدشده‌ای ندارد.</p>}{(u.rewards||[]).map((r,i)=><div className="reward" key={i}><img src={asset(r.image_url)||'/avatars/avatar_2_trophy.png'}/><div><b>{r.name}</b><p>{r.status}</p></div></div>)}</>}</div></div>}
function Support({token}){const[subject,setSubject]=useState(''),[message,setMessage]=useState(''),[tickets,setTickets]=useState([]),[msg,setMsg]=useState('');async function load(){setTickets(await req('/api/support/tickets','GET',null,token))}useEffect(()=>{load()},[]);async function send(){try{await req('/api/support/tickets','POST',{subject,message},token);setSubject('');setMessage('');setMsg('تیکت ارسال شد');load()}catch(e){setMsg(e.message)}}return <section className="card wide"><h2>پشتیبانی</h2><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="موضوع"/><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="پیام"/><button className="main" onClick={send}>ارسال تیکت</button>{msg&&<p className="msg">{msg}</p>}<h3>تیکت‌های من</h3>{tickets.map(t=><div className="row" key={t.id}><span>{t.subject}</span><b>{t.status}</b></div>)}</section>}

createRoot(document.getElementById('root')).render(<App/>);
