import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';
const API=import.meta.env.VITE_API_BASE||'https://api.ghelghelishop.ir';
const avatars=['avatar_1_football.png','avatar_2_trophy.png','avatar_3_star.png','avatar_4_rocket.png','avatar_5_lion.png','avatar_6_tiger.png','avatar_7_eagle.png','avatar_8_target.png','avatar_9_bolt.png','avatar_10_crown.png'];
const fa=n=>new Intl.NumberFormat('fa-IR').format(Number(n||0));
async function req(path,method='GET',body,token){const r=await fetch(API+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'خطا');return d}
function App(){const[token,setToken]=useState(localStorage.token||'');const[mode,setMode]=useState(location.hostname.startsWith('register.')?'register':'login');return <div className="page"><div className="hero"><b>⚽ قل‌قلی شاپ</b><span>ثبت‌نام، ورود و تکمیل پروفایل کاربران</span></div>{token?<Portal token={token} logout={()=>{localStorage.removeItem('token');setToken('')}}/>:<Auth mode={mode} setMode={setMode} done={t=>{localStorage.token=t;setToken(t)}}/>}</div>}
function Auth({mode,setMode,done}){const[f,setF]=useState({mobile:'',password:'',nickname:'',firstName:'',lastName:'',age:'',city:'',province:'',bankAccount:'',profileAvatarKey:avatars[0]});const[msg,setMsg]=useState('');async function submit(e){e.preventDefault();setMsg('');try{const d=mode==='register'?await req('/api/auth/register-password','POST',f):await req('/api/auth/login','POST',{mobile:f.mobile,password:f.password});done(d.token)}catch(x){setMsg(x.message)}}return <form className="card" onSubmit={submit}><h2>{mode==='register'?'ثبت‌نام کاربر':'ورود کاربر'}</h2><div className="tabs"><button type="button" className={mode==='login'?'on':''} onClick={()=>setMode('login')}>ورود</button><button type="button" className={mode==='register'?'on':''} onClick={()=>setMode('register')}>ثبت‌نام</button></div><input placeholder="شماره موبایل" value={f.mobile} onChange={e=>setF({...f,mobile:e.target.value})}/><input placeholder="رمز عبور" type="password" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/>{mode==='register'&&<><input placeholder="نام" onChange={e=>setF({...f,firstName:e.target.value})}/><input placeholder="نام خانوادگی" onChange={e=>setF({...f,lastName:e.target.value})}/><input placeholder="نام مستعار عمومی" onChange={e=>setF({...f,nickname:e.target.value})}/><input placeholder="سن" onChange={e=>setF({...f,age:e.target.value})}/><input placeholder="استان" onChange={e=>setF({...f,province:e.target.value})}/><input placeholder="شهر / محل زندگی" onChange={e=>setF({...f,city:e.target.value})}/><input placeholder="شماره کارت بانکی / شبا" onChange={e=>setF({...f,bankAccount:e.target.value})}/><p>انتخاب عکس پروفایل چت</p><div className="avatars">{avatars.map(a=><img className={f.profileAvatarKey===a?'sel':''} src={`/avatars/${a}`} onClick={()=>setF({...f,profileAvatarKey:a})}/>)}</div></>}<button className="main">{mode==='register'?'ثبت‌نام':'ورود'}</button>{msg&&<p className="msg">{msg}</p>}</form>}
function Portal({token,logout}){const[p,setP]=useState(null),[rewards,setRewards]=useState([]),[code,setCode]=useState(''),[msg,setMsg]=useState('');useEffect(()=>{load()},[]);async function load(){setP(await req('/api/profile','GET',null,token));setRewards(await req('/api/rewards','GET',null,token))}async function redeem(){try{const d=await req('/api/cards/redeem','POST',{code},token);setMsg(d.message);setCode('');load()}catch(e){setMsg(e.message)}}if(!p)return <div className="card">در حال بارگذاری...</div>;const u=p.user;return <div className="grid"><section className="card"><button className="out" onClick={logout}>خروج</button><h2>{u.nickname||u.mobile}</h2><img className="bigavatar" src={`/avatars/${u.profile_avatar_key||avatars[0]}`}/><h3>{fa(u.current_points)} امتیاز فعلی</h3><p>امتیاز تاریخی: {fa(u.lifetime_points)}</p><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="کد کارت"/><button className="main" onClick={redeem}>ثبت کد</button>{msg&&<p className="msg">{msg}</p>}</section><section className="card"><h2>جوایز</h2>{rewards.map(r=><div className="reward"><img src={r.image_url?API+r.image_url:'/avatars/avatar_2_trophy.png'}/><div><b>{r.name}</b><p>{fa(r.required_points)} امتیاز</p></div></div>)}</section></div>}
createRoot(document.getElementById('root')).render(<App/>);
