ALTER TABLE users ADD COLUMN IF NOT EXISTS age INTEGER CHECK (age IS NULL OR (age BETWEEN 1 AND 120));
ALTER TABLE users ADD COLUMN IF NOT EXISTS city VARCHAR(120);
ALTER TABLE users ADD COLUMN IF NOT EXISTS province VARCHAR(120);
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_avatar_key VARCHAR(80);
