import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport:{width:412,height:900}, deviceScaleFactor:2 });
const errs=[];
p.on('pageerror', e=>errs.push('PAGEERR: '+e.message.slice(0,150)));
p.on('console', m=>{ if(m.type()==='error') errs.push('CONSOLE: '+m.text().slice(0,150)); });
await p.goto('https://user.ghelghelishop.ir/', { waitUntil:'networkidle', timeout:60000 });
const ins=await p.$$('input');
await ins[0].fill('09120000001'); await ins[1].fill('Test123456');
await p.click('button:has-text("ورود به حساب کاربری")');
await p.waitForTimeout(5000);
await p.click('button[title="فروشگاه"]');
await p.waitForTimeout(7000);
const t=await p.evaluate(()=>document.body.innerText);
console.log('TEXT LEN:', t.length);
console.log('صندوق:', t.includes('صندوق'), '| ناعدد:', t.includes('ناعدد'), '| ۱۰۰٬۰۰۰:', t.includes('۱۰۰٬۰۰۰'));
console.log('ERRORS:', JSON.stringify(errs.slice(0,5),null,1));
await p.screenshot({ path:'/tmp/prod_shop.png' });
await b.close();
