#!/usr/bin/env bash
#
# Injects the release signing config into the Android project.
#
# WHY THIS EXISTS
# `mobile/android/` is gitignored and regenerated by `flutter create` on every
# CI run, so a signing config committed to the repo would be wiped before the
# build ever sees it. Same reason tool/patch_android.sh exists for the
# manifest permissions.
#
# WHAT GOES WRONG WITHOUT IT
# `flutter build apk --release` does NOT fail when no signing config exists.
# It quietly falls back to the debug key. The APK builds, installs and runs,
# so nothing looks broken — but Cafe Bazaar rejects it, and because Android
# identifies an app by its signature rather than its package name, a debug
# key generated on one machine cannot update an install signed by another.
# Every such release creates permanently un-upgradable installs.
#
# Run from `mobile/` AFTER `flutter create --platforms=android .` and after
# android/key.properties has been written.
set -Eeuo pipefail

KTS="android/app/build.gradle.kts"
GRADLE="android/app/build.gradle"
PROPS="android/key.properties"

[ -f "$PROPS" ] || { echo "ERROR: $PROPS not found"; exit 1; }

if [ -f "$KTS" ]; then
  TARGET="$KTS"; FLAVOUR="kts"
elif [ -f "$GRADLE" ]; then
  TARGET="$GRADLE"; FLAVOUR="groovy"
else
  echo "ERROR: no app build.gradle(.kts) found — run flutter create first"
  exit 1
fi
echo "patching $TARGET ($FLAVOUR)"

python3 - "$TARGET" "$FLAVOUR" <<'PY'
import re, sys

path, flavour = sys.argv[1], sys.argv[2]
src = open(path, encoding='utf-8').read()

if 'ghelgheliRelease' in src:
    print('signing config already present')
    raise SystemExit(0)

if flavour == 'kts':
    # SPLIT IN TWO, and the split is not cosmetic.
    #
    # Gradle requires `plugins {}` to be the first STATEMENT in a .kts script.
    # `import` lines are exempt, but a `val` declaration is not — putting the
    # properties loader above `plugins {}` fails the build with:
    #
    #   only buildscript {}, pluginManagement {} and other plugins {} script
    #   blocks are allowed before plugins {} blocks
    #
    # So imports go at the very top and the loader goes immediately after the
    # plugins block.
    imports = '''// ── release signing (injected by tool/patch_signing.sh) ────────────────────
import java.util.Properties
import java.io.FileInputStream

'''
    loader = '''

// Loaded from android/key.properties, which CI writes from repository
// secrets. android/ is regenerated on every run, so this cannot live in git.
val keystoreProperties = Properties()
val keystorePropertiesFile = rootProject.file("key.properties")
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(FileInputStream(keystorePropertiesFile))
}
'''
    block = '''
    signingConfigs {
        create("ghelgheliRelease") {
            keyAlias = keystoreProperties["keyAlias"] as String
            keyPassword = keystoreProperties["keyPassword"] as String
            storeFile = file(keystoreProperties["storeFile"] as String)
            storePassword = keystoreProperties["storePassword"] as String
        }
    }
'''
    # Point the release build type at it, replacing Flutter's debug default.
    src_new = re.sub(
        r'signingConfig\s*=\s*signingConfigs\.getByName\("debug"\)',
        'signingConfig = signingConfigs.getByName("ghelgheliRelease")',
        src)
    if src_new == src:
        print('WARNING: no debug signingConfig line found to replace')
    src = src_new
else:
    # Groovy has no such ordering restriction.
    imports = ''
    loader = '''
// ── release signing (injected by tool/patch_signing.sh) ────────────────────
def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

'''
    block = '''
    signingConfigs {
        ghelgheliRelease {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
'''
    src_new = re.sub(r'signingConfig\s+signingConfigs\.debug',
                     'signingConfig signingConfigs.ghelgheliRelease', src)
    if src_new == src:
        print('WARNING: no debug signingConfig line found to replace')
    src = src_new

# Imports at the very top; the loader AFTER the plugins block (see above).
if flavour == 'kts':
    src = imports + src
    m = re.search(r'\nplugins\s*\{.*?\n\}\n', src, re.S)
    if m:
        src = src[:m.end()] + loader + src[m.end():]
    else:
        # No plugins block (unusual, but do not silently drop the loader).
        print('WARNING: no plugins block found; placing loader at top')
        src = loader + src
else:
    src = loader + src

# Insert signingConfigs as the first thing inside `android { ... }`.
m = re.search(r'\nandroid\s*\{', src)
if not m:
    print('ERROR: could not find the android block')
    raise SystemExit(1)
at = m.end()
src = src[:at] + block + src[at:]

open(path, 'w', encoding='utf-8').write(src)
print('signing config injected')
PY

echo "--- verifying ---"
grep -q 'ghelgheliRelease' "$TARGET" \
  && echo "  OK   signingConfigs.ghelgheliRelease present" \
  || { echo "  FAIL signing config missing"; exit 1; }

# The release build type must actually USE it. If this check fails the build
# would still succeed and silently ship a debug-signed APK, which is the whole
# failure mode this script exists to prevent.
# Flutter 3.44 expanded the generated release block enough that the assignment
# can sit more than six lines after `release {`. Checking a fixed context
# window produced a false failure even though the exact assignment had been
# injected. Match the assignment itself instead — this cannot be satisfied by
# the signingConfigs declaration above.
if grep -Eq 'signingConfig[[:space:]]*=[[:space:]]*signingConfigs\.getByName\("ghelgheliRelease"\)|signingConfig[[:space:]]+signingConfigs\.ghelgheliRelease' "$TARGET"; then
  echo "  OK   release build type uses it"
else
  echo "  FAIL release build type is not using the release signing config"
  exit 1
fi
