#!/usr/bin/env node
// split-style.mjs — modularize userweb/src/style.css without changing output
// Splits by major comment markers, creates userweb/src/styles/*.css and rewrites style.css as import hub.
// Idempotent, preserves animations verbatim. Verifies that concatenated modules == original.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const stylePath = path.join(root, 'userweb/src/style.css');
const stylesDir = path.join(root, 'userweb/src/styles');

const original = fs.readFileSync(stylePath, 'utf8');
if (original.includes("@import './styles/")) {
  console.log('✓ style.css already modularized — skipping split');
  process.exit(0);
}

const lines = original.split('\n');

// markers we identified
const splits = [
  { name: 'base.css', start: 0, end: 56, label: 'reset/body/card/auth — base' },
  { name: 'games.css', start: 56, end: 437, label: 'Games hub + all boards' },
  { name: 'appbar.css', start: 437, end: 556, label: '2026 refresh: app bar, nav, layout' },
  { name: 'layout-fixes.css', start: 556, end: 732, label: 'layout fixes + wallet' },
  { name: 'tap-support.css', start: 732, end: 967, label: 'Tap game + form fields + notifications' },
  { name: 'chat.css', start: 967, end: 1634, label: 'CHAT rebuilt + shop + profile' },
  { name: 'brand-mark.css', start: 1634, end: lines.length, label: 'Animated brand mark + desktop + wheel' },
];

fs.mkdirSync(stylesDir, { recursive: true });

let reconstructed = '';
for (const s of splits) {
  const chunk = lines.slice(s.start, s.end).join('\n');
  const filePath = path.join(stylesDir, s.name);
  const header = `/* ${s.label} — split from style.css (lines ${s.start+1}-${s.end}) — do not edit style.css directly */\n`;
  fs.writeFileSync(filePath, header + chunk + '\n', 'utf8');
  console.log(`✓ wrote styles/${s.name} (${(chunk.length/1024).toFixed(1)}KB, lines ${s.start+1}-${s.end})`);
  reconstructed += chunk + (s.end < lines.length ? '\n' : '');
}

// Verify concatenation equals original (allow trailing newline)
if (reconstructed.trim() !== original.trim()) {
  console.error('✗ reconstructed mismatch! Aborting — not overwriting style.css');
  // Find first diff
  const a = original.split('\n');
  const b = reconstructed.split('\n');
  for (let i=0;i<Math.min(a.length,b.length);i++) if (a[i]!==b[i]) { console.error(` diff at line ${i+1}`); console.error(`   orig: ${a[i].slice(0,120)}`); console.error(`   recon: ${b[i].slice(0,120)}`); break; }
  process.exit(1);
}
console.log('✓ split verified: 7 modules concatenated == original');

// Now rewrite style.css as import hub
const imports = splits.map(s => `@import './styles/${s.name}';`).join('\n');
const hubHeader = `/* style.css — IMPORT HUB (GENERATED by tools/split-style.mjs)\n   Original 6364 lines split into userweb/src/styles/*.css for maintainability.\n   The cascade order is preserved exactly — do NOT reorder imports.\n   To edit styles, edit the module file, not this hub.\n   Animations are kept verbatim inside their original modules.\n*/\n`;
const hubContent = hubHeader + imports + '\n';

fs.writeFileSync(stylePath, hubContent, 'utf8');
console.log(`✓ rewrote style.css as hub (${hubContent.length} bytes, 7 imports)`);
console.log('  To reverse: cat styles/*.css > style.css (in order)');
