import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:shamsi_date/shamsi_date.dart';
import 'package:socket_io_client/socket_io_client.dart' as io;
import 'api_client.dart';

void main() => runApp(const GhelGheliApp());

class GhelGheliApp extends StatefulWidget { const GhelGheliApp({super.key}); @override State<GhelGheliApp> createState()=>_GhelGheliAppState(); }
class _GhelGheliAppState extends State<GhelGheliApp> {
  final api = ApiClient(); bool ready=false; bool dark=true;
  @override void initState(){ super.initState(); api.loadToken().then((_){ setState(()=>ready=true); }); }
  @override Widget build(BuildContext context){
    final seed = const Color(0xff00d49a);
    final theme = ThemeData(useMaterial3:true, colorScheme: ColorScheme.fromSeed(seedColor: seed, brightness: dark?Brightness.dark:Brightness.light), fontFamily:'Tahoma', scaffoldBackgroundColor: dark?const Color(0xff07111f):const Color(0xfff3f8ff));
    return MaterialApp(
      title:'قل‌قلی', debugShowCheckedModeBanner:false, locale:const Locale('fa'), supportedLocales:const [Locale('fa')], localizationsDelegates:const [GlobalMaterialLocalizations.delegate,GlobalWidgetsLocalizations.delegate,GlobalCupertinoLocalizations.delegate],
      theme: theme, builder:(context,child)=>Directionality(textDirection:TextDirection.rtl, child: child!),
      home: !ready ? const Splash() : api.token==null ? AuthScreen(api:api,onDone:()=>setState((){})) : HomeShell(api:api,onLogout:()async{await api.logout();setState((){});},dark:dark,onTheme:()=>setState(()=>dark=!dark)),
    );
  }
}
class Splash extends StatelessWidget{const Splash({super.key});@override Widget build(BuildContext c)=>const Scaffold(body:Center(child:HeroLogo()));}
class HeroLogo extends StatelessWidget{const HeroLogo({super.key});@override Widget build(BuildContext c)=>Column(mainAxisSize:MainAxisSize.min,children:[Container(width:96,height:96,decoration:BoxDecoration(shape:BoxShape.circle,gradient:const LinearGradient(colors:[Color(0xff00d49a),Color(0xff1c78ff)]),boxShadow:[BoxShadow(color:Colors.tealAccent.withOpacity(.35),blurRadius:45)]),child:const Center(child:Text('⚽',style:TextStyle(fontSize:48)))),const SizedBox(height:18),const Text('قل‌قلی',style:TextStyle(fontSize:32,fontWeight:FontWeight.w900))]);}
class AuthScreen extends StatefulWidget{final ApiClient api; final VoidCallback onDone; const AuthScreen({super.key,required this.api,required this.onDone});@override State<AuthScreen> createState()=>_AuthScreenState();}
class _AuthScreenState extends State<AuthScreen>{ final mobile=TextEditingController(), pass=TextEditingController(), code=TextEditingController(), name=TextEditingController(); bool otpSent=false, registerMode=true, loading=false; String? msg;
  Future<void> run(Future<void> Function() fn) async { setState(()=>loading=true); try{ await fn(); }catch(e){ msg=(e as dynamic).response?.data?['message']?.toString() ?? e.toString(); } finally{ if(mounted)setState(()=>loading=false); } }
  @override Widget build(BuildContext c)=>Scaffold(body:Container(decoration:const BoxDecoration(gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[Color(0xff0b2b4f),Color(0xff07111f)])),child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:CardShell(child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[const HeroLogo(),const SizedBox(height:24),SegmentedButton<bool>(segments:const [ButtonSegment(value:true,label:Text('ثبت‌نام')),ButtonSegment(value:false,label:Text('ورود'))],selected:{registerMode},onSelectionChanged:(s)=>setState(()=>registerMode=s.first)),const SizedBox(height:16),TextField(controller:mobile,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'شماره موبایل')),if(registerMode) ...[const SizedBox(height:10),TextField(controller:name,decoration:const InputDecoration(labelText:'نام مستعار')),const SizedBox(height:10),TextField(controller:code,decoration:InputDecoration(labelText:'کد تایید',suffixIcon:TextButton(onPressed:()=>run(()async{final r=await widget.api.post('/api/auth/request-otp',{'mobile':mobile.text,'purpose':'register'}); msg='کد تایید ارسال شد ${r['devCode']??''}'; otpSent=true;});},child:Text(otpSent?'ارسال مجدد':'ارسال کد'))))],const SizedBox(height:10),TextField(controller:pass,obscureText:true,decoration:const InputDecoration(labelText:'رمز عبور')),const SizedBox(height:18),FilledButton(onPressed:loading?null:()=>run(()async{ if(registerMode){ await widget.api.post('/api/auth/verify-otp',{'mobile':mobile.text,'code':code.text,'purpose':'register'}); final r=await widget.api.post('/api/auth/register',{'mobile':mobile.text,'password':pass.text,'nickname':name.text}); await widget.api.saveToken(r['token']); } else { final r=await widget.api.post('/api/auth/login',{'mobile':mobile.text,'password':pass.text}); await widget.api.saveToken(r['token']); } widget.onDone(); }),child:Text(loading?'لطفاً صبر کنید...':registerMode?'ساخت حساب':'ورود')),if(msg!=null)Padding(padding:const EdgeInsets.only(top:12),child:Text(msg!,style:TextStyle(color:Theme.of(c).colorScheme.primary))) ])))))); }
}
class CardShell extends StatelessWidget{final Widget child; const CardShell({super.key,required this.child});@override Widget build(BuildContext c)=>Container(constraints:const BoxConstraints(maxWidth:520), padding:const EdgeInsets.all(22), decoration:BoxDecoration(borderRadius:BorderRadius.circular(32),color:Theme.of(c).colorScheme.surface.withOpacity(.88),border:Border.all(color:Colors.white.withOpacity(.10)),boxShadow:[BoxShadow(color:Colors.black.withOpacity(.25),blurRadius:45,offset:const Offset(0,18))]),child:child);}
class HomeShell extends StatefulWidget{final ApiClient api; final VoidCallback onLogout; final bool dark; final VoidCallback onTheme; const HomeShell({super.key,required this.api,required this.onLogout,required this.dark,required this.onTheme}); @override State<HomeShell> createState()=>_HomeShellState();}
class _HomeShellState extends State<HomeShell>{int idx=0; Map<String,dynamic>? profile; late final pages=[DashboardPage(api:widget.api,reloadProfile:loadProfile),RewardsPage(api:widget.api),LeaguePage(api:widget.api),ChatPage(api:widget.api),SupportPage(api:widget.api)]; @override void initState(){super.initState();loadProfile();registerFcm();} Future<void> loadProfile() async{try{final d=await widget.api.get('/api/profile');setState(()=>profile=Map<String,dynamic>.from(d));}catch(_){}} Future<void> registerFcm() async{try{await Firebase.initializeApp(); await FirebaseMessaging.instance.requestPermission(); final token=await FirebaseMessaging.instance.getToken(); if(token!=null){await widget.api.patch('/api/profile',{'fcmToken':token});}}catch(_){/* Firebase config is optional in local debug; production needs google-services.json */}}
  @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('قل‌قلی'),actions:[IconButton(onPressed:widget.onTheme,icon:Icon(widget.dark?Icons.light_mode:Icons.dark_mode)),IconButton(onPressed:widget.onLogout,icon:const Icon(Icons.logout))]),body:AnimatedSwitcher(duration:const Duration(milliseconds:350),child:pages[idx]),bottomNavigationBar:NavigationBar(selectedIndex:idx,onDestinationSelected:(i)=>setState(()=>idx=i),destinations:const [NavigationDestination(icon:Icon(Icons.home_rounded),label:'خانه'),NavigationDestination(icon:Icon(Icons.card_giftcard),label:'جوایز'),NavigationDestination(icon:Icon(Icons.emoji_events),label:'لیگ'),NavigationDestination(icon:Icon(Icons.chat_bubble),label:'چت'),NavigationDestination(icon:Icon(Icons.support_agent),label:'پشتیبانی')]),drawer:Drawer(child:SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[const HeroLogo(),const Divider(),Text('امتیاز فعلی: ${faNum(profile?['user']?['current_points']??0)}',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),Text('نام مستعار: ${profile?['user']?['nickname']??'-'}'),const SizedBox(height:12),FilledButton.tonal(onPressed:widget.onLogout,child:const Text('خروج'))]))));}
}
class DashboardPage extends StatefulWidget{final ApiClient api; final Future<void> Function() reloadProfile; const DashboardPage({super.key,required this.api,required this.reloadProfile});@override State<DashboardPage> createState()=>_DashboardPageState();}
class _DashboardPageState extends State<DashboardPage>{Map<String,dynamic>? data; final code=TextEditingController(); String? msg; @override void initState(){super.initState();load();} Future<void> load()async{final d=await widget.api.get('/api/profile');setState(()=>data=Map<String,dynamic>.from(d));}
  @override Widget build(BuildContext c){ final user=data?['user']; final inv=List<Map<String,dynamic>>.from(data?['inventory']??[]); final points=user?['current_points']??0; return RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(18),children:[HeroHeader(points:points,nickname:user?['nickname']??'قهرمان'),const SizedBox(height:18),CardShell(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('ثبت کد کارت',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:10),TextField(controller:code,decoration:const InputDecoration(prefixIcon:Icon(Icons.qr_code_2),labelText:'کد طولانی روی کارت')),const SizedBox(height:12),FilledButton.icon(icon:const Icon(Icons.add_card),label:const Text('ثبت و دریافت امتیاز'),onPressed:()async{try{final r=await widget.api.post('/api/cards/redeem',{'code':code.text}); msg='${r['message']} +${faNum(r['addedPoints'])} امتیاز'; code.clear(); await load(); await widget.reloadProfile();}catch(e){msg=(e as dynamic).response?.data?['message']?.toString()??'خطای شبکه';} if(mounted)setState((){});}),if(msg!=null)Padding(padding:const EdgeInsets.only(top:8),child:Text(msg!))])),const SizedBox(height:18),const Text('موجودی کارت‌ها',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:10),SizedBox(height:220,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:inv.length,separatorBuilder:(_,__)=>const SizedBox(width:14),itemBuilder:(_,i)=>FootballCard(item:inv[i])))]));}
}
class HeroHeader extends StatelessWidget{final int points; final String nickname; const HeroHeader({super.key,required this.points,required this.nickname});@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(24),decoration:BoxDecoration(borderRadius:BorderRadius.circular(34),gradient:const LinearGradient(colors:[Color(0xff00d49a),Color(0xff1c78ff)]),boxShadow:[BoxShadow(color:Colors.tealAccent.withOpacity(.25),blurRadius:35)]),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('سلام $nickname 👋',style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900,color:Colors.white)),const SizedBox(height:10),Text('${faNum(points)} امتیاز فعلی',style:const TextStyle(fontSize:34,fontWeight:FontWeight.w900,color:Colors.white)),const SizedBox(height:16),TweenAnimationBuilder<double>(duration:const Duration(milliseconds:900),tween:Tween(begin:0,end:(points%10000)/10000),builder:(_,v,__)=>ClipRRect(borderRadius:BorderRadius.circular(99),child:LinearProgressIndicator(value:v,minHeight:12,color:Colors.white,backgroundColor:Colors.white24))),const SizedBox(height:8),const Text('پیشرفت تا جایزه بعدی',style:TextStyle(color:Colors.white))]));}
class FootballCard extends StatelessWidget{final Map<String,dynamic> item; const FootballCard({super.key,required this.item});@override Widget build(BuildContext c)=>Container(width:158,padding:const EdgeInsets.all(14),decoration:BoxDecoration(borderRadius:BorderRadius.circular(24),gradient:const LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors:[Color(0xffffd36b),Color(0xff0b2b4f),Color(0xff00d49a)]),boxShadow:[BoxShadow(color:Colors.black.withOpacity(.25),blurRadius:22,offset:const Offset(0,12))]),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Align(alignment:Alignment.topLeft,child:Icon(Icons.auto_awesome,color:Colors.white)),const Spacer(),Text(item['name']??'کارت',style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900,fontSize:18)),Text('تعداد: ${faNum(item['quantity'])}',style:const TextStyle(color:Colors.white)),Text('${faNum(item['point_value'])} امتیاز',style:const TextStyle(color:Colors.white70))]));}
class RewardsPage extends StatefulWidget{final ApiClient api; const RewardsPage({super.key,required this.api});@override State<RewardsPage> createState()=>_RewardsPageState();}
class _RewardsPageState extends State<RewardsPage>{List rewards=[]; @override void initState(){super.initState();widget.api.get('/api/rewards').then((d)=>setState(()=>rewards=d));} @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(18),children:rewards.map((r)=>CardShell(child:ListTile(leading:Icon(r['reward_type']=='cash'?Icons.payments:Icons.inventory_2),title:Text(r['name']??''),subtitle:Text('${faNum(r['required_points'])} امتیاز — ${r['reward_value']}'),trailing:FilledButton.tonal(onPressed:r['eligible']==true?()async{await widget.api.post('/api/rewards/${r['id']}/claim',{}); ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('درخواست جایزه ثبت شد')));}:null,child:const Text('دریافت'))))).toList());}
class LeaguePage extends StatefulWidget{final ApiClient api; const LeaguePage({super.key,required this.api});@override State<LeaguePage> createState()=>_LeaguePageState();}
class _LeaguePageState extends State<LeaguePage>{Map? d; Timer? t; @override void initState(){super.initState();load();t=Timer.periodic(const Duration(seconds:12),(_)=>load());} @override void dispose(){t?.cancel();super.dispose();} Future<void> load()async{final x=await widget.api.get('/api/league/current'); if(mounted)setState(()=>d=x);} @override Widget build(BuildContext c){final entries=List<Map>.from(d?['entries']??[]);final season=d?['season'];final end=season?['ends_at']==null?null:DateTime.parse(season['ends_at']);final left=end==null?'':faNum(end.difference(DateTime.now()).inDays)+' روز تا پایان';return ListView(padding:const EdgeInsets.all(18),children:[HeroHeader(points:entries.isEmpty?0:entries.first['points'],nickname:'لیگ ماهانه'),Text(left,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:12),...entries.asMap().entries.map((e)=>RankTile(rank:e.key+1,row:e.value))]);}}
class RankTile extends StatelessWidget{final int rank; final Map row; const RankTile({super.key,required this.rank,required this.row});@override Widget build(BuildContext c)=>Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(16),decoration:BoxDecoration(borderRadius:BorderRadius.circular(20),color:rank<=3?Colors.amber.withOpacity(.22):Theme.of(c).colorScheme.surfaceContainerHighest),child:Row(children:[CircleAvatar(child:Text(faNum(rank))),const SizedBox(width:12),Expanded(child:Text(row['nickname']??row['first_name']??'کاربر')),Text('${faNum(row['points'])} امتیاز',style:const TextStyle(fontWeight:FontWeight.bold))]));}
class ChatPage extends StatefulWidget{final ApiClient api; const ChatPage({super.key,required this.api});@override State<ChatPage> createState()=>_ChatPageState();}
class _ChatPageState extends State<ChatPage>{final text=TextEditingController(); List msgs=[]; io.Socket? socket; @override void initState(){super.initState();load();socket=io.io(ApiClient.defaultBaseUrl,io.OptionBuilder().setTransports(['websocket']).setAuth({'token':widget.api.token}).build());socket!.on('chat:new',(m)=>setState(()=>msgs=[...msgs,m]));} @override void dispose(){socket?.dispose();super.dispose();} Future<void> load()async{final d=await widget.api.get('/api/chat/messages');setState(()=>msgs=d);} @override Widget build(BuildContext c)=>Column(children:[Expanded(child:ListView.builder(padding:const EdgeInsets.all(14),itemCount:msgs.length,itemBuilder:(_,i){final m=msgs[i];return ListTile(title:Text(m['nickname']??m['first_name']??'کاربر'),subtitle:Text(m['message_text']??''),trailing:IconButton(icon:const Icon(Icons.flag),onPressed:()=>widget.api.post('/api/chat/messages/${m['id']}/report',{})));})),SafeArea(child:Padding(padding:const EdgeInsets.all(12),child:Row(children:[Expanded(child:TextField(controller:text,decoration:const InputDecoration(hintText:'پیام گروهی...'))),IconButton.filled(onPressed:(){socket?.emitWithAck('chat:send',text.text,ack:(r){if(r['ok']==true)text.clear();});},icon:const Icon(Icons.send))])))]);}
class SupportPage extends StatefulWidget{final ApiClient api; const SupportPage({super.key,required this.api});@override State<SupportPage> createState()=>_SupportPageState();}
class _SupportPageState extends State<SupportPage>{final subject=TextEditingController(),msg=TextEditingController();List tickets=[];@override void initState(){super.initState();load();}Future<void> load()async{final d=await widget.api.get('/api/support/tickets');setState(()=>tickets=d);} @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(18),children:[CardShell(child:Column(children:[TextField(controller:subject,decoration:const InputDecoration(labelText:'موضوع')),TextField(controller:msg,decoration:const InputDecoration(labelText:'پیام'),maxLines:4),const SizedBox(height:12),FilledButton(onPressed:()async{await widget.api.post('/api/support/tickets',{'subject':subject.text,'message':msg.text});subject.clear();msg.clear();load();},child:const Text('ارسال تیکت'))])),const SizedBox(height:16),...tickets.map((t)=>Card(child:ListTile(title:Text(t['subject']),subtitle:Text('وضعیت: ${t['status']}'))))]);}
String todayJalali(){final j=Jalali.now();return '${faNum(j.year)}/${faNum(j.month)}/${faNum(j.day)}';}
