import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:image_picker/image_picker.dart';
import 'package:shamsi_date/shamsi_date.dart';
import 'package:socket_io_client/socket_io_client.dart' as io;
import 'api_client.dart';

void main() => runApp(const GhelGheliApp());

class GhelGheliApp extends StatefulWidget {
  const GhelGheliApp({super.key});
  @override State<GhelGheliApp> createState() => _GhelGheliAppState();
}

class _GhelGheliAppState extends State<GhelGheliApp> {
  final api = ApiClient();
  bool ready = false;
  bool dark = true;

  @override void initState() { super.initState(); api.loadToken().then((_) => setState(() => ready = true)); }

  @override Widget build(BuildContext context) {
    final theme = ThemeData(useMaterial3: true, colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xff00d49a), brightness: dark ? Brightness.dark : Brightness.light), fontFamily: 'Tahoma', scaffoldBackgroundColor: dark ? const Color(0xff07111f) : const Color(0xfff3f8ff));
    return MaterialApp(
      title: 'قل‌قلی', debugShowCheckedModeBanner: false, locale: const Locale('fa'), supportedLocales: const [Locale('fa')],
      localizationsDelegates: const [GlobalMaterialLocalizations.delegate, GlobalWidgetsLocalizations.delegate, GlobalCupertinoLocalizations.delegate],
      theme: theme, builder: (context, child) => Directionality(textDirection: TextDirection.rtl, child: child!),
      home: !ready ? const Splash() : api.token == null
          ? AuthScreen(api: api, onDone: () => setState(() {}))
          : api.isAdmin
              ? AdminShell(api: api, onLogout: () async { await api.logout(); setState(() {}); }, dark: dark, onTheme: () => setState(() => dark = !dark))
              : HomeShell(api: api, onLogout: () async { await api.logout(); setState(() {}); }, dark: dark, onTheme: () => setState(() => dark = !dark)),
    );
  }
}

class Splash extends StatelessWidget { const Splash({super.key}); @override Widget build(BuildContext c) => const Scaffold(body: Center(child: HeroLogo())); }
class HeroLogo extends StatelessWidget { const HeroLogo({super.key}); @override Widget build(BuildContext c) => Column(mainAxisSize: MainAxisSize.min, children: [Container(width: 96, height: 96, decoration: BoxDecoration(shape: BoxShape.circle, gradient: const LinearGradient(colors: [Color(0xff00d49a), Color(0xff1c78ff)]), boxShadow: [BoxShadow(color: Colors.tealAccent.withOpacity(.35), blurRadius: 45)]), child: const Center(child: Text('⚽', style: TextStyle(fontSize: 48)))), const SizedBox(height: 18), const Text('قل‌قلی', style: TextStyle(fontSize: 32, fontWeight: FontWeight.w900))]); }
class CardShell extends StatelessWidget { final Widget child; const CardShell({super.key, required this.child}); @override Widget build(BuildContext c) => Container(constraints: const BoxConstraints(maxWidth: 720), padding: const EdgeInsets.all(20), decoration: BoxDecoration(borderRadius: BorderRadius.circular(28), color: Theme.of(c).colorScheme.surface.withOpacity(.9), border: Border.all(color: Colors.white.withOpacity(.10)), boxShadow: [BoxShadow(color: Colors.black.withOpacity(.22), blurRadius: 35, offset: const Offset(0, 14))]), child: child); }

class AuthScreen extends StatefulWidget { final ApiClient api; final VoidCallback onDone; const AuthScreen({super.key, required this.api, required this.onDone}); @override State<AuthScreen> createState() => _AuthScreenState(); }
class _AuthScreenState extends State<AuthScreen> {
  final mobile = TextEditingController(text: 'Admin');
  final pass = TextEditingController(text: 'admin');
  final code = TextEditingController();
  final name = TextEditingController();
  bool registerMode = false;
  bool adminMode = false;
  bool loading = false;
  String? msg;

  Future<void> run(Future<void> Function() fn) async { setState(() { loading = true; msg = null; }); try { await fn(); } catch (e) { msg = apiError(e); } finally { if (mounted) setState(() => loading = false); } }

  @override Widget build(BuildContext c) => Scaffold(body: Container(decoration: const BoxDecoration(gradient: LinearGradient(begin: Alignment.topCenter, end: Alignment.bottomCenter, colors: [Color(0xff0b2b4f), Color(0xff07111f)])), child: Center(child: SingleChildScrollView(padding: const EdgeInsets.all(24), child: CardShell(child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.stretch, children: [
    const HeroLogo(), const SizedBox(height: 22),
    SegmentedButton<String>(segments: const [ButtonSegment(value: 'login', label: Text('ورود کاربر')), ButtonSegment(value: 'register', label: Text('ثبت‌نام')), ButtonSegment(value: 'admin', label: Text('ورود مدیر'))], selected: {adminMode ? 'admin' : registerMode ? 'register' : 'login'}, onSelectionChanged: (s) => setState(() { adminMode = s.first == 'admin'; registerMode = s.first == 'register'; if (adminMode) { mobile.text = 'GhelGheli'; pass.clear(); } })),
    const SizedBox(height: 16),
    TextField(controller: mobile, keyboardType: adminMode ? TextInputType.text : TextInputType.phone, decoration: InputDecoration(labelText: adminMode ? 'نام کاربری مدیر' : 'شماره موبایل')),
    if (registerMode) ...[const SizedBox(height: 10), TextField(controller: name, decoration: const InputDecoration(labelText: 'نام مستعار')), const SizedBox(height: 10), TextField(controller: code, decoration: InputDecoration(labelText: 'کد تایید', suffixIcon: TextButton(onPressed: () => run(() async { final r = await widget.api.post('/api/auth/request-otp', {'mobile': mobile.text, 'purpose': 'register'}); msg = 'کد تایید ارسال شد ${r['devCode'] ?? ''}'; }), child: const Text('ارسال کد'))))],
    const SizedBox(height: 10), TextField(controller: pass, obscureText: true, decoration: const InputDecoration(labelText: 'رمز عبور')), const SizedBox(height: 18),
    FilledButton.icon(icon: Icon(adminMode ? Icons.admin_panel_settings : Icons.login), onPressed: loading ? null : () => run(() async {
      if (adminMode) { final r = await widget.api.post('/api/admin/auth/login', {'username': mobile.text, 'password': pass.text}); await widget.api.saveToken(r['token'], admin: true); }
      else if (registerMode) { await widget.api.post('/api/auth/verify-otp', {'mobile': mobile.text, 'code': code.text, 'purpose': 'register'}); final r = await widget.api.post('/api/auth/register', {'mobile': mobile.text, 'password': pass.text, 'nickname': name.text}); await widget.api.saveToken(r['token']); }
      else { final r = await widget.api.post('/api/auth/login', {'mobile': mobile.text, 'password': pass.text}); await widget.api.saveToken(r['token']); }
      widget.onDone();
    }), label: Text(loading ? 'لطفاً صبر کنید...' : adminMode ? 'ورود به مدیریت' : registerMode ? 'ساخت حساب' : 'ورود')),
    TextButton.icon(onPressed: loading ? null : () => run(() async { final r = await widget.api.post('/api/auth/login', {'mobile': 'Admin', 'password': 'admin'}); await widget.api.saveToken(r['token']); widget.onDone(); }), icon: const Icon(Icons.bolt), label: const Text('ورود تست کاربر با Admin / admin')),
    TextButton.icon(onPressed: loading ? null : () => run(() async { final r = await widget.api.post('/api/admin/auth/login', {'username': 'admin', 'password': 'admin'}); await widget.api.saveToken(r['token'], admin: true); widget.onDone(); }), icon: const Icon(Icons.admin_panel_settings), label: const Text('ورود تست مدیر با admin / admin')),
    if (msg != null) Padding(padding: const EdgeInsets.only(top: 12), child: Text(msg!, style: TextStyle(color: Theme.of(c).colorScheme.primary))),
  ]))))));
}

// -------------------- User app --------------------
class HomeShell extends StatefulWidget { final ApiClient api; final VoidCallback onLogout; final bool dark; final VoidCallback onTheme; const HomeShell({super.key, required this.api, required this.onLogout, required this.dark, required this.onTheme}); @override State<HomeShell> createState() => _HomeShellState(); }
class _HomeShellState extends State<HomeShell> { int idx = 0; Map<String, dynamic>? profile; late final pages = [DashboardPage(api: widget.api, reloadProfile: loadProfile), RewardsPage(api: widget.api), LeaguePage(api: widget.api), ChatPage(api: widget.api), SupportPage(api: widget.api)]; @override void initState() { super.initState(); loadProfile(); registerFcm(); } Future<void> loadProfile() async { try { final d = await widget.api.get('/api/profile'); setState(() => profile = Map<String, dynamic>.from(d)); } catch (_) {} } Future<void> registerFcm() async { try { await Firebase.initializeApp(); await FirebaseMessaging.instance.requestPermission(); final token = await FirebaseMessaging.instance.getToken(); if (token != null) await widget.api.patch('/api/profile', {'fcmToken': token}); } catch (_) {} }
  @override Widget build(BuildContext c) => Scaffold(appBar: AppBar(title: const Text('قل‌قلی'), actions: [IconButton(onPressed: widget.onTheme, icon: Icon(widget.dark ? Icons.light_mode : Icons.dark_mode)), IconButton(onPressed: widget.onLogout, icon: const Icon(Icons.logout))]), body: AnimatedSwitcher(duration: const Duration(milliseconds: 350), child: pages[idx]), bottomNavigationBar: NavigationBar(selectedIndex: idx, onDestinationSelected: (i) => setState(() => idx = i), destinations: const [NavigationDestination(icon: Icon(Icons.home_rounded), label: 'خانه'), NavigationDestination(icon: Icon(Icons.card_giftcard), label: 'جوایز'), NavigationDestination(icon: Icon(Icons.emoji_events), label: 'لیگ'), NavigationDestination(icon: Icon(Icons.chat_bubble), label: 'چت'), NavigationDestination(icon: Icon(Icons.support_agent), label: 'پشتیبانی')])); }
class DashboardPage extends StatefulWidget { final ApiClient api; final Future<void> Function() reloadProfile; const DashboardPage({super.key, required this.api, required this.reloadProfile}); @override State<DashboardPage> createState() => _DashboardPageState(); }
class _DashboardPageState extends State<DashboardPage> { Map<String, dynamic>? data; final code = TextEditingController(); String? msg; bool sending = false; @override void initState() { super.initState(); load(); } Future<void> load() async { final d = await widget.api.get('/api/profile'); setState(() => data = Map<String, dynamic>.from(d)); }
  @override Widget build(BuildContext c) { final user = data?['user']; final inv = List<Map<String, dynamic>>.from(data?['inventory'] ?? []); final points = user?['current_points'] ?? 0; return RefreshIndicator(onRefresh: load, child: ListView(padding: const EdgeInsets.all(18), children: [HeroHeader(points: points, nickname: user?['nickname'] ?? 'قهرمان'), const SizedBox(height: 18), CardShell(child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [const Text('ثبت کد کارت', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w900)), const SizedBox(height: 10), TextField(controller: code, textCapitalization: TextCapitalization.characters, decoration: const InputDecoration(prefixIcon: Icon(Icons.qr_code_2), labelText: 'کد طولانی روی کارت')), const SizedBox(height: 12), FilledButton.icon(icon: const Icon(Icons.add_card), label: Text(sending ? 'در حال ثبت...' : 'ثبت و دریافت امتیاز'), onPressed: sending ? null : () async { setState(() => sending = true); try { final r = await widget.api.post('/api/cards/redeem', {'code': code.text}); msg = '${r['message']} +${faNum(r['addedPoints'])} امتیاز'; code.clear(); await load(); await widget.reloadProfile(); } catch (e) { msg = apiError(e); } finally { if (mounted) setState(() => sending = false); } }), if (msg != null) Padding(padding: const EdgeInsets.only(top: 8), child: Text(msg!))])), const SizedBox(height: 18), const Text('موجودی کارت‌ها', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w900)), const SizedBox(height: 10), SizedBox(height: 225, child: ListView.separated(scrollDirection: Axis.horizontal, itemCount: inv.length, separatorBuilder: (_, __) => const SizedBox(width: 14), itemBuilder: (_, i) => FootballCard(item: inv[i])))])); }
}
class HeroHeader extends StatelessWidget { final int points; final String nickname; const HeroHeader({super.key, required this.points, required this.nickname}); @override Widget build(BuildContext c) => Container(padding: const EdgeInsets.all(24), decoration: BoxDecoration(borderRadius: BorderRadius.circular(34), gradient: const LinearGradient(colors: [Color(0xff00d49a), Color(0xff1c78ff)]), boxShadow: [BoxShadow(color: Colors.tealAccent.withOpacity(.25), blurRadius: 35)]), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('سلام $nickname 👋', style: const TextStyle(fontSize: 24, fontWeight: FontWeight.w900, color: Colors.white)), const SizedBox(height: 10), Text('${faNum(points)} امتیاز فعلی', style: const TextStyle(fontSize: 32, fontWeight: FontWeight.w900, color: Colors.white)), const SizedBox(height: 16), TweenAnimationBuilder<double>(duration: const Duration(milliseconds: 900), tween: Tween(begin: 0, end: (points % 10000) / 10000), builder: (_, v, __) => ClipRRect(borderRadius: BorderRadius.circular(99), child: LinearProgressIndicator(value: v, minHeight: 12, color: Colors.white, backgroundColor: Colors.white24))), const SizedBox(height: 8), const Text('پیشرفت تا جایزه بعدی', style: TextStyle(color: Colors.white))])); }
class FootballCard extends StatelessWidget { final Map<String, dynamic> item; const FootballCard({super.key, required this.item}); @override Widget build(BuildContext c) { final img = fullAssetUrl(item['image_url']); return Container(width: 170, padding: const EdgeInsets.all(14), decoration: BoxDecoration(borderRadius: BorderRadius.circular(24), gradient: const LinearGradient(begin: Alignment.topLeft, end: Alignment.bottomRight, colors: [Color(0xffffd36b), Color(0xff0b2b4f), Color(0xff00d49a)]), boxShadow: [BoxShadow(color: Colors.black.withOpacity(.25), blurRadius: 22, offset: const Offset(0, 12))]), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: ClipRRect(borderRadius: BorderRadius.circular(18), child: img.isNotEmpty ? Image.network(img, width: double.infinity, fit: BoxFit.cover, errorBuilder: (_, __, ___) => const Center(child: Text('⚽', style: TextStyle(fontSize: 44)))) : const Center(child: Text('⚽', style: TextStyle(fontSize: 44))))), const SizedBox(height: 10), Text(item['name'] ?? 'کارت', maxLines: 1, overflow: TextOverflow.ellipsis, style: const TextStyle(color: Colors.white, fontWeight: FontWeight.w900, fontSize: 18)), Text('تعداد: ${faNum(item['quantity'])}', style: const TextStyle(color: Colors.white)), Text('${faNum(item['point_value'])} امتیاز', style: const TextStyle(color: Colors.white70))]); } }
class RewardsPage extends StatefulWidget { final ApiClient api; const RewardsPage({super.key, required this.api}); @override State<RewardsPage> createState() => _RewardsPageState(); }
class _RewardsPageState extends State<RewardsPage> { List rewards = []; @override void initState() { super.initState(); load(); } Future<void> load() async => setState(() {}); @override Widget build(BuildContext c) => FutureBuilder(future: widget.api.get('/api/rewards'), builder: (c, s) { if (!s.hasData) return const Center(child: CircularProgressIndicator()); rewards = s.data as List; return ListView(padding: const EdgeInsets.all(18), children: rewards.map((r) => CardShell(child: ListTile(leading: Icon(r['reward_type'] == 'cash' ? Icons.payments : Icons.inventory_2), title: Text(r['name'] ?? ''), subtitle: Text('${faNum(r['required_points'])} امتیاز — ${r['reward_value']}'), trailing: FilledButton.tonal(onPressed: r['eligible'] == true ? () async { await widget.api.post('/api/rewards/${r['id']}/claim', {}); if (mounted) ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content: Text('درخواست جایزه ثبت شد'))); } : null, child: const Text('دریافت'))))).toList()); }); }
class LeaguePage extends StatefulWidget { final ApiClient api; const LeaguePage({super.key, required this.api}); @override State<LeaguePage> createState() => _LeaguePageState(); }
class _LeaguePageState extends State<LeaguePage> { Map? d; Timer? t; @override void initState() { super.initState(); load(); t = Timer.periodic(const Duration(seconds: 12), (_) => load()); } @override void dispose() { t?.cancel(); super.dispose(); } Future<void> load() async { final x = await widget.api.get('/api/league/current'); if (mounted) setState(() => d = x); } @override Widget build(BuildContext c) { final entries = List<Map>.from(d?['entries'] ?? []); final season = d?['season']; final end = season?['ends_at'] == null ? null : DateTime.parse(season['ends_at']); final left = end == null ? '' : '${faNum(end.difference(DateTime.now()).inDays)} روز تا پایان'; return ListView(padding: const EdgeInsets.all(18), children: [HeroHeader(points: entries.isEmpty ? 0 : entries.first['points'], nickname: 'لیگ ماهانه'), Text(left, style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold)), const SizedBox(height: 12), ...entries.asMap().entries.map((e) => RankTile(rank: e.key + 1, row: e.value))]); } }
class RankTile extends StatelessWidget { final int rank; final Map row; const RankTile({super.key, required this.rank, required this.row}); @override Widget build(BuildContext c) => Container(margin: const EdgeInsets.only(bottom: 10), padding: const EdgeInsets.all(16), decoration: BoxDecoration(borderRadius: BorderRadius.circular(20), color: rank <= 3 ? Colors.amber.withOpacity(.22) : Theme.of(c).colorScheme.surfaceContainerHighest), child: Row(children: [CircleAvatar(child: Text(faNum(rank))), const SizedBox(width: 12), Expanded(child: Text(row['nickname'] ?? row['first_name'] ?? 'کاربر')), Text('${faNum(row['points'])} امتیاز', style: const TextStyle(fontWeight: FontWeight.bold))])); }
class ChatPage extends StatefulWidget { final ApiClient api; const ChatPage({super.key, required this.api}); @override State<ChatPage> createState() => _ChatPageState(); }
class _ChatPageState extends State<ChatPage> { final text = TextEditingController(); List msgs = []; io.Socket? socket; String? error; @override void initState() { super.initState(); load(); socket = io.io(ApiClient.defaultBaseUrl, io.OptionBuilder().setTransports(['websocket']).setAuth({'token': widget.api.token}).build()); socket!.on('chat:new', (m) => setState(() => msgs = [...msgs, m])); } @override void dispose() { socket?.dispose(); super.dispose(); } Future<void> load() async { try { final cfg = await widget.api.get('/api/chat/config'); if (cfg['eligible'] != true) { setState(() => error = 'برای چت باید حداقل ${faNum(cfg['minLifetimePoints'])} امتیاز تاریخی داشته باشید. امتیاز شما: ${faNum(cfg['userLifetimePoints'])}'); return; } final d = await widget.api.get('/api/chat/messages'); setState(() { msgs = d; error = null; }); } catch (e) { setState(() => error = apiError(e)); } } @override Widget build(BuildContext c) => Column(children: [if (error != null) Expanded(child: Center(child: CardShell(child: Text(error!, textAlign: TextAlign.center, style: const TextStyle(fontWeight: FontWeight.bold))))) else Expanded(child: ListView.builder(padding: const EdgeInsets.all(14), itemCount: msgs.length, itemBuilder: (_, i) { final m = msgs[i]; return ListTile(title: Text(m['nickname'] ?? m['first_name'] ?? 'کاربر'), subtitle: Text(m['message_text'] ?? ''), trailing: IconButton(icon: const Icon(Icons.flag), onPressed: () => widget.api.post('/api/chat/messages/${m['id']}/report', {}))); })), SafeArea(child: Padding(padding: const EdgeInsets.all(12), child: Row(children: [Expanded(child: TextField(controller: text, enabled: error == null, decoration: const InputDecoration(hintText: 'پیام گروهی...'))), IconButton.filled(onPressed: error != null ? null : () { socket?.emitWithAck('chat:send', text.text, ack: (r) { if (r['ok'] == true) text.clear(); else ScaffoldMessenger.of(c).showSnackBar(SnackBar(content: Text('${r['error'] ?? 'ارسال نشد'}'))); }); }, icon: const Icon(Icons.send))])))]); }
class SupportPage extends StatefulWidget { final ApiClient api; const SupportPage({super.key, required this.api}); @override State<SupportPage> createState() => _SupportPageState(); }
class _SupportPageState extends State<SupportPage> { final subject = TextEditingController(), msg = TextEditingController(); List tickets = []; @override void initState() { super.initState(); load(); } Future<void> load() async { final d = await widget.api.get('/api/support/tickets'); setState(() => tickets = d); } @override Widget build(BuildContext c) => ListView(padding: const EdgeInsets.all(18), children: [CardShell(child: Column(children: [TextField(controller: subject, decoration: const InputDecoration(labelText: 'موضوع')), TextField(controller: msg, decoration: const InputDecoration(labelText: 'پیام'), maxLines: 4), const SizedBox(height: 12), FilledButton(onPressed: () async { await widget.api.post('/api/support/tickets', {'subject': subject.text, 'message': msg.text}); subject.clear(); msg.clear(); load(); }, child: const Text('ارسال تیکت'))])), const SizedBox(height: 16), ...tickets.map((t) => Card(child: ListTile(title: Text(t['subject']), subtitle: Text('وضعیت: ${t['status']}'))))]); }

// -------------------- Admin app inside Flutter --------------------
class AdminShell extends StatefulWidget { final ApiClient api; final VoidCallback onLogout; final bool dark; final VoidCallback onTheme; const AdminShell({super.key, required this.api, required this.onLogout, required this.dark, required this.onTheme}); @override State<AdminShell> createState() => _AdminShellState(); }
class _AdminShellState extends State<AdminShell> { int idx = 0; late final pages = [AdminDashboard(api: widget.api), AdminCards(api: widget.api), AdminRewards(api: widget.api), AdminLeague(api: widget.api), AdminUsers(api: widget.api), AdminChat(api: widget.api), AdminSupport(api: widget.api), AdminNotifications(api: widget.api), AdminSettings(api: widget.api), AdminAdmins(api: widget.api)]; final titles = ['داشبورد', 'کارت و کد', 'جوایز', 'لیگ', 'کاربران', 'چت', 'پشتیبانی', 'اطلاعیه‌ها', 'تنظیمات', 'ادمین‌ها']; final icons = [Icons.dashboard, Icons.credit_card, Icons.card_giftcard, Icons.emoji_events, Icons.people, Icons.chat, Icons.support_agent, Icons.notifications, Icons.settings, Icons.security];
  @override Widget build(BuildContext c) => Scaffold(appBar: AppBar(title: Text('مدیریت قل‌قلی — ${titles[idx]}'), actions: [IconButton(onPressed: widget.onTheme, icon: Icon(widget.dark ? Icons.light_mode : Icons.dark_mode)), IconButton(onPressed: widget.onLogout, icon: const Icon(Icons.logout))]), drawer: Drawer(child: SafeArea(child: ListView(padding: const EdgeInsets.all(12), children: [const HeroLogo(), const Divider(), ...List.generate(titles.length, (i) => ListTile(selected: idx == i, leading: Icon(icons[i]), title: Text(titles[i]), onTap: () { setState(() => idx = i); Navigator.pop(c); })), const Divider(), ListTile(leading: const Icon(Icons.logout), title: const Text('خروج'), onTap: widget.onLogout)]))), body: pages[idx]); }
}
class AdminGuard extends StatelessWidget { final Future<dynamic> future; final Widget Function(dynamic data) builder; const AdminGuard({super.key, required this.future, required this.builder}); @override Widget build(BuildContext c) => FutureBuilder(future: future, builder: (c, s) { if (s.connectionState != ConnectionState.done) return const Center(child: CircularProgressIndicator()); if (s.hasError) return Center(child: Padding(padding: const EdgeInsets.all(20), child: Text(apiError(s.error!)))); return builder(s.data); }); }
class StatCard extends StatelessWidget { final String title; final Object value; const StatCard(this.title, this.value, {super.key}); @override Widget build(BuildContext c) => CardShell(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title), const SizedBox(height: 6), Text(faNum(value), style: const TextStyle(fontSize: 26, fontWeight: FontWeight.w900))])); }
class AdminDashboard extends StatefulWidget { final ApiClient api; const AdminDashboard({super.key, required this.api}); @override State<AdminDashboard> createState() => _AdminDashboardState(); }
class _AdminDashboardState extends State<AdminDashboard> { late Future data = widget.api.get('/api/admin/dashboard'); @override Widget build(BuildContext c) => RefreshIndicator(onRefresh: () async => setState(() => data = widget.api.get('/api/admin/dashboard')), child: AdminGuard(future: data, builder: (d) { final e = List<Map>.from(d['league']['entries'] ?? []); return ListView(padding: const EdgeInsets.all(16), children: [Wrap(spacing: 12, runSpacing: 12, children: [SizedBox(width: 170, child: StatCard('کاربران', d['users'])), SizedBox(width: 170, child: StatCard('کدهای امروز', d['usedCodesToday'])), SizedBox(width: 170, child: StatCard('کدهای ماه', d['usedCodesThisMonth'])), SizedBox(width: 170, child: StatCard('درخواست‌های در انتظار', d['pendingClaims']))]), const SizedBox(height: 16), CardShell(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('لیدربرد زنده', style: TextStyle(fontWeight: FontWeight.w900, fontSize: 18)), ...e.map((r) => RankTile(rank: int.tryParse('${r['rank']}') ?? 0, row: r))]))]; })); }
class AdminCards extends StatefulWidget { final ApiClient api; const AdminCards({super.key, required this.api}); @override State<AdminCards> createState() => _AdminCardsState(); }
class _AdminCardsState extends State<AdminCards> { List types = [], codes = []; Map? report; String? selectedType; final name = TextEditingController(), point = TextEditingController(), desc = TextEditingController(), imageUrl = TextEditingController(), singleCode = TextEditingController(), bulkCodes = TextEditingController(); bool loading = false; @override void initState() { super.initState(); load(); } Future<void> load() async { types = await widget.api.get('/api/admin/card-types'); codes = await widget.api.get('/api/admin/card-codes'); selectedType ??= types.isNotEmpty ? types.first['id'] : null; if (mounted) setState(() {}); } Future<void> pickImage() async { final x = await ImagePicker().pickImage(source: ImageSource.gallery, imageQuality: 82); if (x != null) { imageUrl.text = await widget.api.uploadAdminImage(x.path); setState(() {}); } } Future<void> createType() async { setState(() => loading = true); try { await widget.api.post('/api/admin/card-types', {'name': name.text, 'pointValue': int.tryParse(point.text) ?? 0, 'description': desc.text, 'imageUrl': imageUrl.text}); name.clear(); point.clear(); desc.clear(); imageUrl.clear(); await load(); } catch (e) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(apiError(e)))); } finally { if (mounted) setState(() => loading = false); } } Future<void> addSingle() async { if (selectedType == null) return; await widget.api.post('/api/admin/card-codes', {'cardTypeId': selectedType, 'code': singleCode.text}); singleCode.clear(); await load(); } Future<void> addBulk() async { if (selectedType == null) return; final r = await widget.api.post('/api/admin/card-codes/bulk', {'cardTypeId': selectedType, 'rawCodes': bulkCodes.text}); report = Map.from(r); await load(); setState(() {}); }
  @override Widget build(BuildContext c) => ListView(padding: const EdgeInsets.all(16), children: [CardShell(child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [const Text('تعریف نوع کارت و عکس', style: TextStyle(fontWeight: FontWeight.w900, fontSize: 18)), TextField(controller: name, decoration: const InputDecoration(labelText: 'نام کارت')), TextField(controller: point, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'امتیاز')), TextField(controller: desc, decoration: const InputDecoration(labelText: 'توضیحات')), Row(children: [Expanded(child: TextField(controller: imageUrl, decoration: const InputDecoration(labelText: 'آدرس عکس/آپلودشده'))), IconButton.filledTonal(onPressed: pickImage, icon: const Icon(Icons.photo_library))]), const SizedBox(height: 10), FilledButton(onPressed: loading ? null : createType, child: const Text('ذخیره کارت'))])), const SizedBox(height: 12), CardShell(child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [const Text('ثبت کد برای کارت', style: TextStyle(fontWeight: FontWeight.w900, fontSize: 18)), DropdownButtonFormField(value: selectedType, items: types.map<DropdownMenuItem<String>>((t) => DropdownMenuItem(value: t['id'], child: Text('${t['name']} — ${faNum(t['point_value'])}'))).toList(), onChanged: (v) => setState(() => selectedType = v)), TextField(controller: singleCode, textCapitalization: TextCapitalization.characters, decoration: const InputDecoration(labelText: 'ثبت تکی کد')), FilledButton.tonal(onPressed: addSingle, child: const Text('ثبت یک کد')), TextField(controller: bulkCodes, textCapitalization: TextCapitalization.characters, minLines: 5, maxLines: 10, decoration: const InputDecoration(labelText: 'ثبت دسته‌جمعی؛ هر خط یک کد یا جدا با کاما')), FilledButton(onPressed: addBulk, child: const Text('ثبت دسته‌جمعی کدها')), if (report != null) Padding(padding: const EdgeInsets.only(top: 10), child: Text('موفق: ${faNum(report!['insertedCount'])} | تکراری فایل: ${faNum(report!['duplicateInFileCount'])} | تکراری دیتابیس: ${faNum(report!['duplicateInDbCount'])} | نامعتبر: ${faNum(report!['invalidCount'])}'))])), const SizedBox(height: 12), CardShell(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('نوع کارت‌ها'), ...types.take(20).map((t) => ListTile(leading: t['image_url'] != null && '${t['image_url']}'.isNotEmpty ? Image.network(fullAssetUrl(t['image_url']), width: 44, height: 44, fit: BoxFit.cover) : const Icon(Icons.credit_card), title: Text(t['name']), subtitle: Text('${faNum(t['point_value'])} امتیاز')))])), CardShell(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('آخرین کدها'), ...codes.take(40).map((x) => ListTile(title: Text(x['code'] ?? ''), subtitle: Text('${x['card_type_name']} — ${x['status']} — ${x['used_by_mobile'] ?? ''}')))]))]); }
class AdminRewards extends StatefulWidget { final ApiClient api; const AdminRewards({super.key, required this.api}); @override State<AdminRewards> createState() => _AdminRewardsState(); }
class _AdminRewardsState extends State<AdminRewards> { List rewards = [], claims = []; final name = TextEditingController(), points = TextEditingController(), value = TextEditingController(), desc = TextEditingController(); String type = 'cash'; @override void initState() { super.initState(); load(); } Future<void> load() async { rewards = await widget.api.get('/api/admin/rewards'); claims = await widget.api.get('/api/admin/reward-claims'); setState(() {}); } Future<void> add() async { await widget.api.post('/api/admin/rewards', {'name': name.text, 'requiredPoints': int.tryParse(points.text) ?? 0, 'rewardType': type, 'rewardValue': value.text, 'description': desc.text, 'displayOrder': rewards.length + 1}); name.clear(); points.clear(); value.clear(); desc.clear(); await load(); } Future<void> status(String id, String s) async { await widget.api.patch('/api/admin/reward-claims/$id', {'status': s}); await load(); }
  @override Widget build(BuildContext c) => ListView(padding: const EdgeInsets.all(16), children: [CardShell(child: Column(children: [const Text('جایزه جدید'), TextField(controller: name, decoration: const InputDecoration(labelText: 'نام')), TextField(controller: points, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'امتیاز مورد نیاز')), DropdownButtonFormField(value: type, items: const [DropdownMenuItem(value: 'cash', child: Text('نقدی')), DropdownMenuItem(value: 'physical', child: Text('فیزیکی'))], onChanged: (v) => setState(() => type = v!)), TextField(controller: value, decoration: const InputDecoration(labelText: 'مبلغ/توضیح جایزه')), TextField(controller: desc, decoration: const InputDecoration(labelText: 'توضیحات')), FilledButton(onPressed: add, child: const Text('ذخیره جایزه'))])), const SizedBox(height: 12), CardShell(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('سطح‌های جایزه'), ...rewards.map((r) => ListTile(title: Text(r['name']), subtitle: Text('${faNum(r['required_points'])} — ${r['reward_value']}')))])), CardShell(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('درخواست‌های جایزه'), ...claims.map((r) => ListTile(title: Text('${r['mobile']} — ${r['reward_name']}'), subtitle: Text(r['status']), trailing: PopupMenuButton<String>(onSelected: (s) => status(r['id'], s), itemBuilder: (_) => const [PopupMenuItem(value: 'approved', child: Text('تایید')), PopupMenuItem(value: 'paid', child: Text('پرداخت‌شده')), PopupMenuItem(value: 'rejected', child: Text('رد'))])))]))]); }
class AdminLeague extends StatefulWidget { final ApiClient api; const AdminLeague({super.key, required this.api}); @override State<AdminLeague> createState() => _AdminLeagueState(); }
class _AdminLeagueState extends State<AdminLeague> { Map? d; List prizes = List.generate(10, (i) => {'rank': i + 1, 'amount': 0}); @override void initState() { super.initState(); load(); } Future<void> load() async { d = await widget.api.get('/api/admin/league'); prizes = List<Map>.from(d?['season']?['prize_table'] ?? prizes); setState(() {}); } Future<void> save() async { await widget.api.patch('/api/admin/league/current/prizes', {'prizeTable': prizes}); await load(); }
  @override Widget build(BuildContext c) => ListView(padding: const EdgeInsets.all(16), children: [CardShell(child: Column(children: [const Text('جوایز رتبه‌ها'), ...List.generate(prizes.length, (i) => TextFormField(initialValue: '${prizes[i]['amount']}', keyboardType: TextInputType.number, decoration: InputDecoration(labelText: 'رتبه ${faNum(prizes[i]['rank'])}'), onChanged: (v) => prizes[i]['amount'] = int.tryParse(v) ?? 0)), FilledButton(onPressed: save, child: const Text('ذخیره جوایز لیگ'))])), const SizedBox(height: 12), CardShell(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('لیدربرد'), ...List<Map>.from(d?['entries'] ?? []).map((r) => RankTile(rank: int.tryParse('${r['rank']}') ?? 0, row: r))]))]); }
class AdminUsers extends StatefulWidget { final ApiClient api; const AdminUsers({super.key, required this.api}); @override State<AdminUsers> createState() => _AdminUsersState(); }
class _AdminUsersState extends State<AdminUsers> { List rows = []; final q = TextEditingController(); @override void initState() { super.initState(); load(); } Future<void> load() async { rows = await widget.api.get('/api/admin/users?search=${Uri.encodeComponent(q.text)}'); setState(() {}); } Future<void> points(String id) async { final c = TextEditingController(); final p = await showDialog<String>(context: context, builder: (_) => AlertDialog(title: const Text('امتیاز دستی'), content: TextField(controller: c, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'مثبت یا منفی')), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('لغو')), FilledButton(onPressed: () => Navigator.pop(context, c.text), child: const Text('ثبت'))])); if (p != null) { await widget.api.post('/api/admin/users/$id/points', {'points': int.tryParse(p) ?? 0, 'reason': 'تغییر از اپ مدیریت'}); await load(); } }
  @override Widget build(BuildContext c) => ListView(padding: const EdgeInsets.all(16), children: [CardShell(child: Row(children: [Expanded(child: TextField(controller: q, decoration: const InputDecoration(labelText: 'جستجوی کاربر'))), IconButton.filled(onPressed: load, icon: const Icon(Icons.search))])), ...rows.map((u) => Card(child: ListTile(title: Text('${u['mobile']} — ${u['nickname'] ?? ''}'), subtitle: Text('${faNum(u['current_points'])} امتیاز — ${u['status']}'), trailing: PopupMenuButton<String>(onSelected: (s) async { if (s == 'points') await points(u['id']); else { await widget.api.patch('/api/admin/users/${u['id']}/status', {'status': s, 'reason': 'از اپ مدیریت'}); await load(); } }, itemBuilder: (_) => [const PopupMenuItem(value: 'points', child: Text('تغییر امتیاز')), PopupMenuItem(value: u['status'] == 'active' ? 'blocked' : 'active', child: Text(u['status'] == 'active' ? 'مسدود' : 'رفع مسدودی'))]))))]); }
class AdminChat extends StatefulWidget { final ApiClient api; const AdminChat({super.key, required this.api}); @override State<AdminChat> createState() => _AdminChatState(); }
class _AdminChatState extends State<AdminChat> { List rows = []; @override void initState() { super.initState(); load(); } Future<void> load() async { rows = await widget.api.get('/api/admin/chat/messages'); setState(() {}); } @override Widget build(BuildContext c) => ListView(padding: const EdgeInsets.all(16), children: rows.map((m) => Card(child: ListTile(title: Text(m['nickname'] ?? m['mobile'] ?? ''), subtitle: Text(m['message_text'] ?? ''), trailing: PopupMenuButton<String>(onSelected: (s) async { if (s == 'delete') await widget.api.patch('/api/admin/chat/messages/${m['id']}/delete', {'reason': 'از اپ مدیریت'}); if (s == 'ban') await widget.api.patch('/api/admin/chat/users/${m['user_id']}/ban', {'minutes': 1440, 'reason': 'از اپ مدیریت'}); await load(); }, itemBuilder: (_) => const [PopupMenuItem(value: 'delete', child: Text('حذف پیام')), PopupMenuItem(value: 'ban', child: Text('بن چت ۲۴ ساعت'))])))).toList()); }
class AdminSupport extends StatefulWidget { final ApiClient api; const AdminSupport({super.key, required this.api}); @override State<AdminSupport> createState() => _AdminSupportState(); }
class _AdminSupportState extends State<AdminSupport> { List tickets = [], msgs = []; Map? sel; final reply = TextEditingController(); @override void initState() { super.initState(); load(); } Future<void> load() async { tickets = await widget.api.get('/api/admin/support/tickets'); setState(() {}); } Future<void> open(Map t) async { sel = t; msgs = await widget.api.get('/api/admin/support/tickets/${t['id']}/messages'); setState(() {}); } Future<void> send() async { if (sel == null) return; await widget.api.post('/api/admin/support/tickets/${sel!['id']}/messages', {'message': reply.text}); reply.clear(); await open(sel!); await load(); }
  @override Widget build(BuildContext c) => ListView(padding: const EdgeInsets.all(16), children: [CardShell(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('تیکت‌ها'), ...tickets.map((t) => ListTile(selected: sel?['id'] == t['id'], title: Text('${t['mobile']} — ${t['subject']}'), subtitle: Text(t['status']), onTap: () => open(Map.from(t))))])), if (sel != null) CardShell(child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Text('پاسخ به: ${sel!['subject']}', style: const TextStyle(fontWeight: FontWeight.w900)), ...msgs.map((m) => Align(alignment: m['sender_type'] == 'admin' ? Alignment.centerLeft : Alignment.centerRight, child: Container(margin: const EdgeInsets.all(6), padding: const EdgeInsets.all(10), decoration: BoxDecoration(color: m['sender_type'] == 'admin' ? Colors.teal.withOpacity(.25) : Colors.blueGrey.withOpacity(.25), borderRadius: BorderRadius.circular(14)), child: Text(m['message_text'])))), TextField(controller: reply, maxLines: 3, decoration: const InputDecoration(labelText: 'پاسخ')), FilledButton(onPressed: send, child: const Text('ارسال پاسخ'))]))]); }
class AdminNotifications extends StatefulWidget { final ApiClient api; const AdminNotifications({super.key, required this.api}); @override State<AdminNotifications> createState() => _AdminNotificationsState(); }
class _AdminNotificationsState extends State<AdminNotifications> { final title = TextEditingController(), body = TextEditingController(); @override Widget build(BuildContext c) => ListView(padding: const EdgeInsets.all(16), children: [CardShell(child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [const Text('ارسال اطلاعیه همگانی'), TextField(controller: title, decoration: const InputDecoration(labelText: 'عنوان')), TextField(controller: body, maxLines: 5, decoration: const InputDecoration(labelText: 'متن')), FilledButton(onPressed: () async { await widget.api.post('/api/admin/notifications/broadcast', {'title': title.text, 'body': body.text}); title.clear(); body.clear(); if (mounted) ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content: Text('اطلاعیه ارسال شد'))); }, child: const Text('ارسال'))]))]); }
class AdminSettings extends StatefulWidget { final ApiClient api; const AdminSettings({super.key, required this.api}); @override State<AdminSettings> createState() => _AdminSettingsState(); }
class _AdminSettingsState extends State<AdminSettings> { final chatMin = TextEditingController(); String? msg; @override void initState() { super.initState(); load(); } Future<void> load() async { final d = await widget.api.get('/api/admin/settings/chat'); chatMin.text = '${d['minLifetimePoints'] ?? 0}'; if (mounted) setState(() {}); } Future<void> save() async { try { final r = await widget.api.patch('/api/admin/settings/chat', {'minLifetimePoints': int.tryParse(chatMin.text) ?? 0, 'reason': 'تنظیم از اپ مدیریت'}); msg = r['message'] ?? 'ذخیره شد'; } catch (e) { msg = apiError(e); } if (mounted) setState(() {}); }
  @override Widget build(BuildContext c) => ListView(padding: const EdgeInsets.all(16), children: [CardShell(child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [const Text('تنظیمات چت کاربران', style: TextStyle(fontWeight: FontWeight.w900, fontSize: 18)), const SizedBox(height: 8), const Text('کاربر فقط وقتی می‌تواند وارد چت شود و پیام بفرستد که حداقل این مقدار امتیاز تاریخی داشته باشد. امتیاز تاریخی بعد از دریافت جایزه صفر نمی‌شود.'), TextField(controller: chatMin, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'حداقل امتیاز تاریخی برای چت')), const SizedBox(height: 10), FilledButton.icon(onPressed: save, icon: const Icon(Icons.save), label: const Text('ذخیره محدودیت چت')), if (msg != null) Padding(padding: const EdgeInsets.only(top: 10), child: Text(msg!))]))]); }
class AdminAdmins extends StatefulWidget { final ApiClient api; const AdminAdmins({super.key, required this.api}); @override State<AdminAdmins> createState() => _AdminAdminsState(); }
class _AdminAdminsState extends State<AdminAdmins> { List admins = [], logs = []; final u = TextEditingController(), p = TextEditingController(); String role = 'support'; @override void initState() { super.initState(); load(); } Future<void> load() async { admins = await widget.api.get('/api/admin/admins'); logs = await widget.api.get('/api/admin/audit-log'); setState(() {}); } Future<void> add() async { await widget.api.post('/api/admin/admins', {'username': u.text, 'password': p.text, 'role': role}); u.clear(); p.clear(); await load(); }
  @override Widget build(BuildContext c) => ListView(padding: const EdgeInsets.all(16), children: [CardShell(child: Column(children: [const Text('ادمین جدید'), TextField(controller: u, decoration: const InputDecoration(labelText: 'نام کاربری')), TextField(controller: p, decoration: const InputDecoration(labelText: 'رمز عبور')), DropdownButtonFormField(value: role, items: const [DropdownMenuItem(value: 'super_admin', child: Text('مدیر کل')), DropdownMenuItem(value: 'support', child: Text('پشتیبان')), DropdownMenuItem(value: 'observer', child: Text('ناظر'))], onChanged: (v) => setState(() => role = v!),), FilledButton(onPressed: add, child: const Text('ایجاد ادمین'))])), CardShell(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('ادمین‌ها'), ...admins.map((a) => ListTile(title: Text(a['username']), subtitle: Text(a['role'])))])), CardShell(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Audit Log'), ...logs.take(80).map((l) => Text('${l['username'] ?? 'سیستم'} — ${l['action']} — ${l['created_at']}'))]))]); }

String todayJalali() { final j = Jalali.now(); return '${faNum(j.year)}/${faNum(j.month)}/${faNum(j.day)}'; }
